#include "TTree.h"
#include "TLorentzVector.h"
#include <iostream>
#include <cmath>

class etau_tree {
private:
  TTree *tree;
  TTree *original;

public:
  // variables copied directly tree to tree
  Float_t run, lumi, evt, genweight, genpX, genpY, vispX, vispY, genpT, genM, met, metphi, metSig, metcov00, metcov01, metcov10, metcov11, met_EESDown, met_EESUp, met_JESUp, met_JESDown;
  Float_t met_MESDown, met_MESUp, met_PESUp, met_PESDown, met_TESUp, met_TESDown, met_UESUp, met_UESDown, met_JERDown, met_JERUp, metphi_EESDown, metphi_EESUp, metphi_JESUp;
  Float_t metphi_JESDown, metphi_MESDown, metphi_MESUp, metphi_PESUp, metphi_PESDown, metphi_TESUp, metphi_TESDown, metphi_UESUp, metphi_UESDown, metphi_JERDown, metphi_JERUp;
  Float_t mvaMet, mvaMetcov00, mvaMetcov11, mvaMetcov10, mvaMetcov01, mvaMetphi, dphi_12, dphi_emet, dphi_taumet, passEle25, passEle27, filterEle25;
  Float_t pt_top1, pt_top2, njets, nbtag, njetspt20, njets_JESDown, njetspt20_JESDown, njets_JESUp, njetspt20_JESUp, gen_match_1, gen_match_2, pt_tt, pzetavis, pzetamiss;
  Float_t m_vis, l2_decayMode, mt_1, dZ_1, d0_1, iso_1, q_1, mt_2, dZ_2, d0_2, iso_2, q_2, m_coll, m_coll_uesU, m_coll_uesD, m_coll_jesU, m_coll_jesD, m_coll_tesU, m_coll_tesD;
  Float_t againstMuonTight3_2, againstMuonLoose3_2, againstElectronVLooseMVA6_2, againstElectronLooseMVA6_2, againstElectronMediumMVA6_2, againstElectronTightMVA6_2;
  Float_t againstElectronVTightMVA6_2, byLooseCombinedIsolationDeltaBetaCorr3Hits_2, byMediumCombinedIsolationDeltaBetaCorr3Hits_2, byTightCombinedIsolationDeltaBetaCorr3Hits_2;
  Float_t byCombinedIsolationDeltaBetaCorrRaw3Hits_2, byIsolationMVA3oldDMwLTraw_2, byIsolationMVA3newDMwLTraw_2, byVLooseIsolationMVArun2v1DBoldDMwLT_2, byLooseIsolationMVArun2v1DBoldDMwLT_2;
  Float_t byMediumIsolationMVArun2v1DBoldDMwLT_2, byTightIsolationMVArun2v1DBoldDMwLT_2, byVTightIsolationMVArun2v1DBoldDMwLT_2, byVVTightIsolationMVArun2v1DBoldDMwLT_2;
  Float_t neutralIsoPtSum_2, chargedIsoPtSum_2, puCorrPtSum_2, decayModeFinding_2, decayModeFindingNewDMs_2, jpt_1, jpt_2, jeta_1, jeta_2, jphi_1, jphi_2, jcsv_1, jcsv_2, bpt_1, bpt_2;
  Float_t beta_1, beta_2, bphi_1, bphi_2, bcsv_1, bcsv_2, NUP, npu, npv, rho, extratau_veto, isZtt;

  // temporary storage variables
  Float_t eVetoZTTp001dxyzR0, muVetoZTTp001dxyzR0, dielectronVeto, vbfMass_JetEnUp, vbfMass_JetEnDown;

  // new variables to store in new tree
  Float_t met_px, met_py, extraelec_veto, dilepton_veto, m_1, pt_1, eta_1, phi_1, e_1, px_1, py_1, pz_1, m_2, pt_2, eta_2, phi_2, e_2, px_2, py_2, pz_2, dijetphi, hdijetphi, visjeteta, isZet;
  Float_t jdeta, jdphi, mjj, njetingap20, njetingap, dijetpt, njetingap20_JESUp, njetingap_JESUp, mjj_JESUp, jdeta_JESUp, njetingap20_JESDown, njetingap_JESDown, mjj_JESDown, jdeta_JESDown;
  Float_t gen_Higgs_pt, gen_Higgs_mass, weight;

  // forgotten
  Float_t byIsolationMVA3oldDMwoLTraw_2, trigweight_2, byIsolationMVA3newDMwoLTraw_2, filterEle27, ePt, eMass, ePhi, eEta, tPhi, tEta, tMass, tPt, numGenJets, vbfDeta_JetEnDown, vbfDeta_JetEnUp, vbfDphi;
  Float_t vbfDphi_JetEnDown, vbfDphi_JetEnUp, vbfMass, vbfJetVeto20, vbfJetVeto20_JetEnDown, vbfJetVeto20_JetEnUp, vbfJetVeto30, vbfJetVeto30_JetEnDown, vbfJetVeto30_JetEnUp, eGenPdgId, vbfDeta, extramuon_veto;
  Float_t eMVANonTrigWP80, ePassesConversionVeto, eMissingHits, e_t_DR;

  etau_tree (TTree* orig, TTree* itree);
  virtual ~etau_tree () {};
  TTree* do_skimming();
};

etau_tree::etau_tree(TTree* Original, TTree* itree) :
  tree(itree),
  original(Original)
 {

   tree->Branch("run", &run, "run/I");
   tree->Branch("lumi", &lumi, "lumi/I");
   tree->Branch("evt", &evt, "evt/I");
   tree->Branch("isZtt", &isZtt, "isZtt/O");
   tree->Branch("isZet", &isZet, "isZet/O");
   tree->Branch("NUP", &NUP, "NUP/I");
   tree->Branch("genpX", &genpX, "genpX/F");
   tree->Branch("genpY", &genpY, "genpY/F");
   tree->Branch("genM", &genM, "genM/F");
   tree->Branch("genpT", &genpT, "genpT/F");
   tree->Branch("vispX", &vispX, "vispX/F");
   tree->Branch("vispY", &vispY, "vispY/F");
   tree->Branch("npv", &npv, "npv/F");
   tree->Branch("npu", &npu, "npu/F");
   tree->Branch("rho", &rho, "rho/F");
   tree->Branch("pt_1", &pt_1, "pt_1/F");
   tree->Branch("px_1", &px_1, "px_1/F");
   tree->Branch("py_1", &py_1, "py_1/F");
   tree->Branch("pz_1", &pz_1, "pz_1/F");
   tree->Branch("phi_1", &phi_1, "phi_1/F");
   tree->Branch("eta_1", &eta_1, "eta_1/F");
   tree->Branch("m_1", &m_1, "m_1/F");
   tree->Branch("e_1", &e_1, "e_1/F");
   tree->Branch("q_1", &q_1, "q_1/F");
   tree->Branch("d0_1", &d0_1, "d0_1/F");
   tree->Branch("dZ_1", &dZ_1, "dZ_1/F");
   tree->Branch("mt_1", &mt_1, "mt_1/F");
   tree->Branch("iso_1", &iso_1, "iso_1/F");
   tree->Branch("pt_2", &pt_2, "pt_2/F");
   tree->Branch("phi_2", &phi_2, "phi_2/F");
   tree->Branch("eta_2", &eta_2, "eta_2/F");
   tree->Branch("px_2", &px_2, "px_2/F");
   tree->Branch("py_2", &py_2, "py_2/F");
   tree->Branch("pz_2", &pz_2, "pz_2/F");
   tree->Branch("m_2", &m_2, "m_2/F");
   tree->Branch("e_2", &m_2, "e_2/F");
   tree->Branch("q_2", &q_2, "q_2/F");
   tree->Branch("d0_2", &d0_2, "d0_2/F");
   tree->Branch("dZ_2", &dZ_2, "dZ_2/F");
   tree->Branch("mt_2", &mt_2, "mt_2/F");
   tree->Branch("iso_2", &iso_2, "iso_2/F");
   tree->Branch("l2_decayMode", &l2_decayMode, "l2_decayMode/F");
   tree->Branch("trigweight_2", &trigweight_2, "trigweight_2/F");
   tree->Branch("againstElectronLooseMVA6_2", &againstElectronLooseMVA6_2, "againstElectronLooseMVA6_2/F");
   tree->Branch("againstElectronMediumMVA6_2", &againstElectronMediumMVA6_2, "againstElectronMediumMVA6_2/F");
   tree->Branch("againstElectronTightMVA6_2", &againstElectronTightMVA6_2, "againstElectronTightMVA6_2/F");
   tree->Branch("againstElectronVLooseMVA6_2", &againstElectronVLooseMVA6_2, "againstElectronVLooseMVA6_2/F");
   tree->Branch("againstElectronVTightMVA6_2", &againstElectronVTightMVA6_2, "againstElectronVTightMVA6_2/F");
   tree->Branch("againstMuonLoose3_2", &againstMuonLoose3_2, "againstMuonLoose3_2/F");
   tree->Branch("againstMuonTight3_2", &againstMuonTight3_2, "againstMuonTight3_2/F");
   tree->Branch("byMediumIsolationMVArun2v1DBoldDMwLT_2", &byMediumIsolationMVArun2v1DBoldDMwLT_2, "byMediumIsolationMVArun2v1DBoldDMwLT_2/F");
   tree->Branch("byTightIsolationMVArun2v1DBoldDMwLT_2", &byTightIsolationMVArun2v1DBoldDMwLT_2, "byTightIsolationMVArun2v1DBoldDMwLT_2/F");
   tree->Branch("byVTightIsolationMVArun2v1DBoldDMwLT_2", &byVTightIsolationMVArun2v1DBoldDMwLT_2, "byVTightIsolationMVArun2v1DBoldDMwLT_2/F");
   tree->Branch("byVVTightIsolationMVArun2v1DBoldDMwLT_2", &byVVTightIsolationMVArun2v1DBoldDMwLT_2, "byVVTightIsolationMVArun2v1DBoldDMwLT_2/F");
   tree->Branch("byIsolationMVA3oldDMwoLTraw_2", &byIsolationMVA3oldDMwoLTraw_2, "byIsolationMVA3oldDMwoLTraw_2/F");
   tree->Branch("byIsolationMVA3oldDMwLTraw_2", &byIsolationMVA3oldDMwLTraw_2, "byIsolationMVA3oldDMwLTraw_2/F");
   tree->Branch("byIsolationMVA3newDMwoLTraw_2", &byIsolationMVA3newDMwoLTraw_2, "byIsolationMVA3newDMwoLTraw_2/F");
   tree->Branch("byIsolationMVA3newDMwLTraw_2", &byIsolationMVA3newDMwLTraw_2, "byIsolationMVA3newDMwLTraw_2/F");
   tree->Branch("chargedIsoPtSum_2", &chargedIsoPtSum_2, "chargedIsoPtSum_2/F");
   tree->Branch("decayModeFinding_2", &decayModeFinding_2, "decayModeFinding_2/F");
   tree->Branch("decayModeFindingNewDMs_2", &decayModeFindingNewDMs_2, "decayModeFindingNewDMs_2/F");
   tree->Branch("neutralIsoPtSum_2", &neutralIsoPtSum_2, "neutralIsoPtSum_2/F");
   tree->Branch("puCorrPtSum_2", &puCorrPtSum_2, "puCorrPtSum_2/F");
   tree->Branch("pt_tt", &pt_tt, "pt_tt/F");
   tree->Branch("m_vis", &m_vis, "m_vis/F");
   tree->Branch("met", &met, "met/F");
   tree->Branch("metSig", &metSig, "metSig/F");
   tree->Branch("metcov00", &metcov00, "metcov00/F");
   tree->Branch("metcov10", &metcov10, "metcov10/F");
   tree->Branch("metcov11", &metcov11, "metcov11/F");
   tree->Branch("metcov01", &metcov01, "metcov01/F");
   tree->Branch("metphi", &metphi, "metphi/F");
   tree->Branch("mvaMet", &mvaMet, "mvaMet/F");
   tree->Branch("mvaMetcov00", &mvaMetcov00, "mvaMetcov00/F");
   tree->Branch("mvaMetcov10", &mvaMetcov10, "mvaMetcov10/F");
   tree->Branch("mvaMetcov11", &mvaMetcov11, "mvaMetcov11/F");
   tree->Branch("mvaMetcov01", &mvaMetcov01, "mvaMetcov01/F");
   tree->Branch("mvaMetphi", &mvaMetphi, "mvaMetphi/F");
   tree->Branch("met_py", &met_py, "met_py/F");
   tree->Branch("met_px", &met_px, "met_px/F");
   tree->Branch("pzetavis", &pzetavis, "pzetavis/F");
   tree->Branch("pzetamiss", &pzetamiss, "pzetamiss/F");
   tree->Branch("mjj", &mjj, "mjj/F");
   tree->Branch("jdeta", &jdeta, "jdeta/F");
   tree->Branch("njetingap", &njetingap, "njetingap/I");
   tree->Branch("njetingap20", &njetingap20, "njetingap20/I");
   tree->Branch("mjj_JESUp", &mjj_JESUp, "mjj_JESUp/F");
   tree->Branch("jdeta_JESUp", &jdeta_JESUp, "jdeta_JESUp/F");
   tree->Branch("njetingap_JESUp", &njetingap_JESUp, "njetingap_JESUp/I");
   tree->Branch("njetingap20_JESUp", &njetingap20_JESUp, "njetingap20_JESUp/I");
   tree->Branch("mjj_JESDown", &mjj_JESDown, "mjj_JESDown/F");
   tree->Branch("jdeta_JESDown", &jdeta_JESDown, "jdeta_JESDown/F");
   tree->Branch("njetingap_JESDown", &njetingap_JESDown, "njetingap_JESDown/I");
   tree->Branch("njetingap20_JESDown", &njetingap20_JESDown, "njetingap20_JESDown/I");
   tree->Branch("gen_match_1", &gen_match_1, "gen_match_1/I");
   tree->Branch("gen_match_2", &gen_match_2, "gen_match_2/I");
   tree->Branch("nbtag", &nbtag, "nbtag/I");
   tree->Branch("njets", &njets, "njets/I");
   tree->Branch("njetspt20", &njetspt20, "njetspt20/I");
   tree->Branch("njets_JESUp", &njets_JESUp, "njets_JESUp/I");
   tree->Branch("njetspt20_JESUp", &njetspt20_JESUp, "njetspt20_JESUp/I");
   tree->Branch("njets_JESDown", &njets_JESDown, "njets_JESDown/I");
   tree->Branch("njetspt20_JESDown", &njetspt20_JESDown, "njetspt20_JESDown/I");
   tree->Branch("jpt_1", &jpt_1, "jpt_1/F");
   tree->Branch("jeta_1", &jeta_1, "jeta_1/F");
   tree->Branch("jphi_1", &jphi_1, "jphi_1/F");
   tree->Branch("jcsv_1", &jcsv_1, "jcsv_1/F");
   tree->Branch("jpt_2", &jpt_2, "jpt_2/F");
   tree->Branch("jeta_2", &jeta_2, "jeta_2/F");
   tree->Branch("jphi_2", &jphi_2, "jphi_2/F");
   tree->Branch("jcsv_2", &jcsv_2, "jcsv_2/F");
   tree->Branch("bpt_1", &bpt_1, "bpt_1/F");
   tree->Branch("beta_1", &beta_1, "beta_1/F");
   tree->Branch("bphi_1", &bphi_1, "bphi_1/F");
   tree->Branch("bcsv_1", &bcsv_1, "bcsv_1/F");
   tree->Branch("bpt_2", &bpt_2, "bpt_2/F");
   tree->Branch("beta_2", &beta_2, "beta_2/F");
   tree->Branch("bphi_2", &bphi_2, "bphi_2/F");
   tree->Branch("bcsv_2", &bcsv_2, "bcsv_2/F");
   tree->Branch("passEle25", &passEle25, "passEle25/F");
   tree->Branch("passEle27", &passEle27, "passEle27/F");
   tree->Branch("pt_top1", &pt_top1, "pt_top1/F");
   tree->Branch("filterEle25", &filterEle25, "filterEle25/F");
   tree->Branch("filterEle27", &filterEle27, "filterEle27/F");
   tree->Branch("pt_top2", &pt_top2, "pt_top2/F");
   tree->Branch("genweight", &genweight, "genweight/F");
   tree->Branch("gen_Higgs_pt", &gen_Higgs_pt, "gen_Higgs_pt/F");
   tree->Branch("gen_Higgs_mass", &gen_Higgs_mass, "gen_Higgs_mass/F");


   // read input tree
   original->SetBranchAddress("run", &run);
   original->SetBranchAddress("lumi", &lumi);
   original->SetBranchAddress("evt", &evt);
   original->SetBranchAddress("GenWeight", &genweight);
   original->SetBranchAddress("genpX", &genpX);
   original->SetBranchAddress("genpY", &genpY);
   original->SetBranchAddress("vispX", &vispX);
   original->SetBranchAddress("vispY", &vispY);
   original->SetBranchAddress("genpT", &genpT);
   original->SetBranchAddress("genM", &genM);
   original->SetBranchAddress("type1_pfMetEt", &met);
   original->SetBranchAddress("type1_pfMetPhi", &metphi);
   original->SetBranchAddress("metSig", &metSig);
   original->SetBranchAddress("metcov00", &metcov00);
   original->SetBranchAddress("metcov01", &metcov01);
   original->SetBranchAddress("metcov10", &metcov10);
   original->SetBranchAddress("metcov11", &metcov11);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_ElectronEnDown", &metphi_EESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_ElectronEnUp", &metphi_EESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_JetEnDown", &metphi_JESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_JetEnUp", &metphi_JESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_JetResDown", &metphi_JERDown);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_JetResUp", &metphi_JERUp);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_MuonEnDown", &metphi_MESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_MuonEnUp", &metphi_MESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_PhotonEnDown", &metphi_PESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_PhotonEnUp", &metphi_PESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_TauEnDown", &metphi_TESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_TauEnUp", &metphi_TESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_UnclusteredEnDown", &metphi_UESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPhi_UnclusteredEnUp", &metphi_UESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPt_ElectronEnDown", &met_EESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPt_ElectronEnUp", &met_EESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPt_JetEnDown", &met_JESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPt_JetEnUp", &met_JESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPt_JetResDown", &met_JERDown);
   original->SetBranchAddress("type1_pfMet_shiftedPt_JetResUp", &met_JERUp);
   original->SetBranchAddress("type1_pfMet_shiftedPt_MuonEnDown", &met_MESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPt_MuonEnUp", &met_MESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPt_PhotonEnDown", &met_PESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPt_PhotonEnUp", &met_PESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPt_TauEnDown", &met_TESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPt_TauEnUp", &met_TESUp);
   original->SetBranchAddress("type1_pfMet_shiftedPt_UnclusteredEnDown", &met_UESDown);
   original->SetBranchAddress("type1_pfMet_shiftedPt_UnclusteredEnUp", &met_UESUp);
   original->SetBranchAddress("e_t_MvaMet", &mvaMet);
   original->SetBranchAddress("e_t_MvaMetCovMatrix00", &mvaMetcov00);
   original->SetBranchAddress("e_t_MvaMetCovMatrix01", &mvaMetcov01);
   original->SetBranchAddress("e_t_MvaMetCovMatrix10", &mvaMetcov10);
   original->SetBranchAddress("e_t_MvaMetCovMatrix11", &mvaMetcov11);
   original->SetBranchAddress("e_t_MvaMetPhi", &mvaMetphi);
   original->SetBranchAddress("genpT", &gen_Higgs_pt);
   original->SetBranchAddress("genM", &gen_Higgs_mass);
   original->SetBranchAddress("e_t_DPhi", &dphi_12);
   original->SetBranchAddress("eDPhiToPfMet_type1", &dphi_emet);
   original->SetBranchAddress("tDPhiToPfMet_type1", &dphi_taumet);
   original->SetBranchAddress("singleE25eta2p1TightPass", &passEle25);
   original->SetBranchAddress("singleE27TightPass", &passEle27);
   original->SetBranchAddress("eMatchesEle25TightFilter", &filterEle25);
   original->SetBranchAddress("topQuarkPt1", &pt_top1);
   original->SetBranchAddress("topQuarkPt2", &pt_top2);
   original->SetBranchAddress("GenWeight", &weight);
   original->SetBranchAddress("jetVeto30", &njets);
   original->SetBranchAddress("bjetCISVVeto20Medium", &nbtag);
   original->SetBranchAddress("jetVeto20", &njetspt20);
   original->SetBranchAddress("jetVeto20_JetEnDown", &njets_JESDown);
   original->SetBranchAddress("jetVeto20_JetEnUp", &njetspt20_JESDown);
   original->SetBranchAddress("jetVeto30_JetEnDown", &njets_JESUp);
   original->SetBranchAddress("jetVeto30_JetEnUp", &njetspt20_JESUp);
   original->SetBranchAddress("eZTTGenMatching", &gen_match_1);
   original->SetBranchAddress("tZTTGenMatching", &gen_match_2);
   original->SetBranchAddress("e_t_pt_tt", &pt_tt);
   original->SetBranchAddress("e_t_PZetaVis", &pzetavis);
   original->SetBranchAddress("e_t_PZeta", &pzetamiss);
   original->SetBranchAddress("e_t_Mass", &m_vis);
   original->SetBranchAddress("tDecayMode", &l2_decayMode);
   original->SetBranchAddress("eMtToPfMet_type1", &mt_1);
   original->SetBranchAddress("ePVDZ", &dZ_1);
   original->SetBranchAddress("ePVDXY", &d0_1);
   original->SetBranchAddress("eIsoDB03", &iso_1);
   original->SetBranchAddress("eCharge", &q_1);
   original->SetBranchAddress("tMtToPfMet_type1", &mt_1);
   original->SetBranchAddress("tPVDXY", &dZ_2);
   original->SetBranchAddress("tPVDZ", &d0_2);
   original->SetBranchAddress("tByIsolationMVArun2v1DBoldDMwLTraw", &iso_2);
   original->SetBranchAddress("tCharge", &q_2);
   original->SetBranchAddress("e_t_collinearmass", &m_coll);
   original->SetBranchAddress("e_t_collinearmass_UnclusteredEnUp", &m_coll_uesU);
   original->SetBranchAddress("e_t_collinearmass_UnclusteredEnDown", &m_coll_uesD);
   original->SetBranchAddress("e_t_collinearmass_JetEnUp", &m_coll_jesU);
   original->SetBranchAddress("e_t_collinearmass_JetEnDown", &m_coll_jesD);
   original->SetBranchAddress("e_t_collinearmass_TauEnUp", &m_coll_tesU);
   original->SetBranchAddress("e_t_collinearmass_TauEnDown", &m_coll_tesD);
   original->SetBranchAddress("tAgainstMuonTight3", &againstMuonTight3_2);
   original->SetBranchAddress("tAgainstMuonLoose3", &againstMuonLoose3_2);
   original->SetBranchAddress("tAgainstElectronVLooseMVA6", &againstElectronVLooseMVA6_2);
   original->SetBranchAddress("tAgainstElectronLooseMVA6", &againstElectronLooseMVA6_2);
   original->SetBranchAddress("tAgainstElectronMediumMVA6", &againstElectronMediumMVA6_2);
   original->SetBranchAddress("tAgainstElectronTightMVA6", &againstElectronTightMVA6_2);
   original->SetBranchAddress("tAgainstElectronVTightMVA6", &againstElectronVTightMVA6_2);
   original->SetBranchAddress("tByLooseCombinedIsolationDeltaBetaCorr3Hits", &byLooseCombinedIsolationDeltaBetaCorr3Hits_2);
   original->SetBranchAddress("tByMediumCombinedIsolationDeltaBetaCorr3Hits", &byMediumCombinedIsolationDeltaBetaCorr3Hits_2);
   original->SetBranchAddress("tByTightCombinedIsolationDeltaBetaCorr3Hits", &byTightCombinedIsolationDeltaBetaCorr3Hits_2);
   original->SetBranchAddress("tByCombinedIsolationDeltaBetaCorrRaw3Hits", &byCombinedIsolationDeltaBetaCorrRaw3Hits_2);
   original->SetBranchAddress("tByIsolationMVArun2v1DBoldDMwLTraw", &byIsolationMVA3oldDMwLTraw_2);
   original->SetBranchAddress("tByIsolationMVArun2v1DBnewDMwLTraw", &byIsolationMVA3newDMwLTraw_2);
   original->SetBranchAddress("tByVLooseIsolationMVArun2v1DBoldDMwLT", &byVLooseIsolationMVArun2v1DBoldDMwLT_2);
   original->SetBranchAddress("tByLooseIsolationMVArun2v1DBoldDMwLT", &byLooseIsolationMVArun2v1DBoldDMwLT_2);
   original->SetBranchAddress("tByMediumIsolationMVArun2v1DBoldDMwLT", &byMediumIsolationMVArun2v1DBoldDMwLT_2);
   original->SetBranchAddress("tByTightIsolationMVArun2v1DBoldDMwLT", &byTightIsolationMVArun2v1DBoldDMwLT_2);
   original->SetBranchAddress("tByVTightIsolationMVArun2v1DBoldDMwLT", &byVTightIsolationMVArun2v1DBoldDMwLT_2);
   original->SetBranchAddress("tByVVTightIsolationMVArun2v1DBoldDMwLT", &byVVTightIsolationMVArun2v1DBoldDMwLT_2);
   original->SetBranchAddress("tNeutralIsoPtSum", &neutralIsoPtSum_2);
   original->SetBranchAddress("tChargedIsoPtSum", &chargedIsoPtSum_2);
   original->SetBranchAddress("tPuCorrPtSum", &puCorrPtSum_2);
   original->SetBranchAddress("tDecayModeFinding", &decayModeFinding_2);
   original->SetBranchAddress("tDecayModeFindingNewDMs", &decayModeFindingNewDMs_2);
   original->SetBranchAddress("j1eta", &jeta_1);
   original->SetBranchAddress("j1csv", &jcsv_1);
   original->SetBranchAddress("j1phi", &jphi_1);
   original->SetBranchAddress("j1pt", &jpt_1);
   original->SetBranchAddress("j2csv", &jcsv_2);
   original->SetBranchAddress("j2eta", &jeta_2);
   original->SetBranchAddress("j2phi", &jphi_2);
   original->SetBranchAddress("j2pt", &jpt_2);
   original->SetBranchAddress("jb1csv", &bcsv_1);
   original->SetBranchAddress("jb1eta", &beta_1);
   original->SetBranchAddress("jb1phi", &bphi_1);
   original->SetBranchAddress("jb1pt", &bpt_1);
   original->SetBranchAddress("jb2csv", &bcsv_2);
   original->SetBranchAddress("jb2eta", &beta_2);
   original->SetBranchAddress("jb2phi", &bphi_2);
   original->SetBranchAddress("jb2pt", &bpt_2);
   original->SetBranchAddress("NUP", &NUP);
   original->SetBranchAddress("nTruePU", &npu);
   original->SetBranchAddress("numGenJets", &numGenJets);
   original->SetBranchAddress("nvtx", &npv);
   original->SetBranchAddress("rho", &rho);
   original->SetBranchAddress("tauVetoPt20Loose3HitsVtx", &extratau_veto);
   original->SetBranchAddress("isZtautau", &isZtt);

   original->SetBranchAddress("eVetoZTTp001dxyzR0", &eVetoZTTp001dxyzR0);
   original->SetBranchAddress("muVetoZTTp001dxyzR0", &muVetoZTTp001dxyzR0);
   original->SetBranchAddress("dielectronVeto", &dielectronVeto);
   original->SetBranchAddress("ePt", &ePt);
   original->SetBranchAddress("eMass", &eMass);
   original->SetBranchAddress("eEta", &eEta);
   original->SetBranchAddress("ePhi", &ePhi);
   original->SetBranchAddress("tPt", &tPt);
   original->SetBranchAddress("tMass", &tMass);
   original->SetBranchAddress("tEta", &tEta);
   original->SetBranchAddress("tPhi", &tPhi);
   original->SetBranchAddress("vbfDeta", &vbfDeta);
   original->SetBranchAddress("vbfDeta_JetEnDown", &vbfDeta_JetEnDown);
   original->SetBranchAddress("vbfDeta_JetEnUp", &vbfDeta_JetEnUp);
   original->SetBranchAddress("vbfDphi", &vbfDphi);
   original->SetBranchAddress("vbfDphi_JetEnDown", &vbfDphi_JetEnDown);
   original->SetBranchAddress("vbfDphi_JetEnUp", &vbfDphi_JetEnUp);
   original->SetBranchAddress("vbfMass", &vbfMass);
   original->SetBranchAddress("vbfJetVeto20", &vbfJetVeto20);
   original->SetBranchAddress("vbfJetVeto20_JetEnDown", &vbfJetVeto20_JetEnDown);
   original->SetBranchAddress("vbfJetVeto20_JetEnUp", &vbfJetVeto20_JetEnUp);
   original->SetBranchAddress("vbfJetVeto30", &vbfJetVeto30);
   original->SetBranchAddress("vbfJetVeto30_JetEnDown", &vbfJetVeto30_JetEnDown);
   original->SetBranchAddress("vbfJetVeto30_JetEnUp", &vbfJetVeto30_JetEnUp);
   original->SetBranchAddress("eGenPdgId", &eGenPdgId);
   original->SetBranchAddress("eMVANonTrigWP80", &eMVANonTrigWP80);
   original->SetBranchAddress("ePassesConversionVeto", &ePassesConversionVeto);
   original->SetBranchAddress("eMissingHits", &eMissingHits);
   original->SetBranchAddress("e_t_DR", &e_t_DR);
   original->SetBranchAddress("vbfMass_JetEnUp", &vbfMass_JetEnUp);
   original->SetBranchAddress("vbfMass_JetEnDown", &vbfMass_JetEnDown);







   // original->SetBranchAddress("tByIsolationMVArun2v1DBdR03oldDMwLTraw", &tByIsolationMVArun2v1DBdR03oldDMwLTraw);
   // original->SetBranchAddress("tByIsolationMVArun2v1PWdR03oldDMwLTraw", &tByIsolationMVArun2v1PWdR03oldDMwLTraw);
   // original->SetBranchAddress("tByIsolationMVArun2v1PWnewDMwLTraw", &tByIsolationMVArun2v1PWnewDMwLTraw);
   // original->SetBranchAddress("tByIsolationMVArun2v1PWoldDMwLTraw", &tByIsolationMVArun2v1PWoldDMwLTraw);
   // original->SetBranchAddress("tByLooseIsolationMVArun2v1DBdR03oldDMwLT", &tByLooseIsolationMVArun2v1DBdR03oldDMwLT);
   // original->SetBranchAddress("tByLooseIsolationMVArun2v1DBnewDMwLT", &tByLooseIsolationMVArun2v1DBnewDMwLT);
   // original->SetBranchAddress("tByLooseIsolationMVArun2v1PWdR03oldDMwLT", &tByLooseIsolationMVArun2v1PWdR03oldDMwLT);
   // original->SetBranchAddress("tByLooseIsolationMVArun2v1PWnewDMwLT", &tByLooseIsolationMVArun2v1PWnewDMwLT);
   // original->SetBranchAddress("tByLooseIsolationMVArun2v1PWoldDMwLT", &tByLooseIsolationMVArun2v1PWoldDMwLT);
   // original->SetBranchAddress("tByMediumIsolationMVArun2v1DBdR03oldDMwLT", &tByMediumIsolationMVArun2v1DBdR03oldDMwLT);
   // original->SetBranchAddress("tByMediumIsolationMVArun2v1DBnewDMwLT", &tByMediumIsolationMVArun2v1DBnewDMwLT);
   // original->SetBranchAddress("tByMediumIsolationMVArun2v1PWdR03oldDMwLT", &tByMediumIsolationMVArun2v1PWdR03oldDMwLT);
   // original->SetBranchAddress("tByMediumIsolationMVArun2v1PWnewDMwLT", &tByMediumIsolationMVArun2v1PWnewDMwLT);
   // original->SetBranchAddress("tByMediumIsolationMVArun2v1PWoldDMwLT", &tByMediumIsolationMVArun2v1PWoldDMwLT);
   // original->SetBranchAddress("tByPhotonPtSumOutsideSignalCone", &tByPhotonPtSumOutsideSignalCone);
   // original->SetBranchAddress("tByTightIsolationMVArun2v1DBdR03oldDMwLT", &tByTightIsolationMVArun2v1DBdR03oldDMwLT);
   // original->SetBranchAddress("tByTightIsolationMVArun2v1DBnewDMwLT", &tByTightIsolationMVArun2v1DBnewDMwLT);
   // original->SetBranchAddress("tByTightIsolationMVArun2v1PWdR03oldDMwLT", &tByTightIsolationMVArun2v1PWdR03oldDMwLT);
   // original->SetBranchAddress("tByTightIsolationMVArun2v1PWnewDMwLT", &tByTightIsolationMVArun2v1PWnewDMwLT);
   // original->SetBranchAddress("tByTightIsolationMVArun2v1PWoldDMwLT", &tByTightIsolationMVArun2v1PWoldDMwLT);
   // original->SetBranchAddress("tByVLooseIsolationMVArun2v1DBdR03oldDMwLT", &tByVLooseIsolationMVArun2v1DBdR03oldDMwLT);
   // original->SetBranchAddress("tByVLooseIsolationMVArun2v1DBnewDMwLT", &tByVLooseIsolationMVArun2v1DBnewDMwLT);
   // original->SetBranchAddress("tByVLooseIsolationMVArun2v1PWdR03oldDMwLT", &tByVLooseIsolationMVArun2v1PWdR03oldDMwLT);
   // original->SetBranchAddress("tByVLooseIsolationMVArun2v1PWnewDMwLT", &tByVLooseIsolationMVArun2v1PWnewDMwLT);
   // original->SetBranchAddress("tByVLooseIsolationMVArun2v1PWoldDMwLT", &tByVLooseIsolationMVArun2v1PWoldDMwLT);
   // original->SetBranchAddress("tByVTightIsolationMVArun2v1DBdR03oldDMwLT", &tByVTightIsolationMVArun2v1DBdR03oldDMwLT);
   // original->SetBranchAddress("tByVTightIsolationMVArun2v1DBnewDMwLT", &tByVTightIsolationMVArun2v1DBnewDMwLT);
   // original->SetBranchAddress("tByVTightIsolationMVArun2v1PWdR03oldDMwLT", &tByVTightIsolationMVArun2v1PWdR03oldDMwLT);
   // original->SetBranchAddress("tByVTightIsolationMVArun2v1PWnewDMwLT", &tByVTightIsolationMVArun2v1PWnewDMwLT);
   // original->SetBranchAddress("tByVTightIsolationMVArun2v1PWoldDMwLT", &tByVTightIsolationMVArun2v1PWoldDMwLT);
   // original->SetBranchAddress("tByVVTightIsolationMVArun2v1DBdR03oldDMwLT", &tByVVTightIsolationMVArun2v1DBdR03oldDMwLT);
   // original->SetBranchAddress("tByVVTightIsolationMVArun2v1DBnewDMwLT", &tByVVTightIsolationMVArun2v1DBnewDMwLT);
   // original->SetBranchAddress("tByVVTightIsolationMVArun2v1PWdR03oldDMwLT", &tByVVTightIsolationMVArun2v1PWdR03oldDMwLT);
   // original->SetBranchAddress("tByVVTightIsolationMVArun2v1PWnewDMwLT", &tByVVTightIsolationMVArun2v1PWnewDMwLT);
   // original->SetBranchAddress("tByVVTightIsolationMVArun2v1PWoldDMwLT", &tByVVTightIsolationMVArun2v1PWoldDMwLT);
   // original->SetBranchAddress("tAgainstElectronMVA6Raw", &tAgainstElectronMVA6Raw);
   // original->SetBranchAddress("tAgainstElectronMVA6category", &tAgainstElectronMVA6category);
   // original->SetBranchAddress("e_t_CosThetaStar", &e_t_CosThetaStar);
   // original->SetBranchAddress("e_t_Eta", &e_t_Eta);
   // original->SetBranchAddress("e_t_Mass_TauEnDown", &e_t_Mass_TauEnDown);
   // original->SetBranchAddress("e_t_Mass_TauEnUp", &e_t_Mass_TauEnUp);
   // original->SetBranchAddress("e_t_Mt", &e_t_Mt);
   // original->SetBranchAddress("e_t_MtTotal", &e_t_MtTotal);
   // original->SetBranchAddress("e_t_Mt_TauEnDown", &e_t_Mt_TauEnDown);
   // original->SetBranchAddress("e_t_Mt_TauEnUp", &e_t_Mt_TauEnUp);
   // original->SetBranchAddress("e_t_PZetaLess0p85PZetaVis", &e_t_PZetaLess0p85PZetaVis);
   // original->SetBranchAddress("e_t_Phi", &e_t_Phi);
   // original->SetBranchAddress("e_t_Pt", &e_t_Pt);
   // original->SetBranchAddress("e_t_SS", &e_t_SS);
   // original->SetBranchAddress("e_t_ToMETDPhi_Ty1", &e_t_ToMETDPhi_Ty1);
   // original->SetBranchAddress("e_t_collinearmass_MuEnDown", &e_t_collinearmass_MuEnDown);
   // original->SetBranchAddress("e_t_collinearmass_MuEnUp", &e_t_collinearmass_MuEnUp);
   // original->SetBranchAddress("e_t_collinearmass_EleEnDown", &e_t_collinearmass_EleEnDown);
   // original->SetBranchAddress("e_t_collinearmass_EleEnUp", &e_t_collinearmass_EleEnUp);
   //  original->SetBranchAddress("EmbPtWeight", &EmbPtWeight);
   //  original->SetBranchAddress("Eta", &Eta);
   //  original->SetBranchAddress("Flag_BadChargedCandidateFilter", &Flag_BadChargedCandidateFilter);
   //  original->SetBranchAddress("Flag_BadPFMuonFilter", &Flag_BadPFMuonFilter);
   //  original->SetBranchAddress("Flag_EcalDeadCellTriggerPrimitiveFilter", &Flag_EcalDeadCellTriggerPrimitiveFilter);
   //  original->SetBranchAddress("Flag_HBHENoiseFilter", &Flag_HBHENoiseFilter);
   //  original->SetBranchAddress("Flag_HBHENoiseIsoFilter", &Flag_HBHENoiseIsoFilter);
   //  original->SetBranchAddress("Flag_badCloneMuonFilter", &Flag_badCloneMuonFilter);
   //  original->SetBranchAddress("Flag_badGlobalMuonFilter", &Flag_badGlobalMuonFilter);
   //  original->SetBranchAddress("Flag_eeBadScFilter", &Flag_eeBadScFilter);
   //  original->SetBranchAddress("Flag_globalTightHalo2016Filter", &Flag_globalTightHalo2016Filter);
   //  original->SetBranchAddress("Flag_goodVertices", &Flag_goodVertices);
   //  original->SetBranchAddress("Ht", &Ht);
   //  original->SetBranchAddress("LT", &LT);
   //  original->SetBranchAddress("Mass", &Mass);
   //  original->SetBranchAddress("MassError", &MassError);
   //  original->SetBranchAddress("MassErrord1", &MassErrord1);
   //  original->SetBranchAddress("MassErrord2", &MassErrord2);
   //  original->SetBranchAddress("MassErrord3", &MassErrord3);
   //  original->SetBranchAddress("MassErrord4", &MassErrord4);
   //  original->SetBranchAddress("Mt", &Mt);
   //  original->SetBranchAddress("Phi", &Phi);
   //  original->SetBranchAddress("Pt", &Pt);
   //  original->SetBranchAddress("bjetCISVVeto20Loose", &bjetCISVVeto20Loose);
   //  original->SetBranchAddress("bjetCISVVeto20Tight", &bjetCISVVeto20Tight);
   //  original->SetBranchAddress("bjetCISVVeto30Loose", &bjetCISVVeto30Loose);
   //  original->SetBranchAddress("bjetCISVVeto30Medium", &bjetCISVVeto30Medium);
   //  original->SetBranchAddress("bjetCISVVeto30Tight", &bjetCISVVeto30Tight);
   //  original->SetBranchAddress("charge", &charge);
   //  original->SetBranchAddress("dimuonVeto", &dimuonVeto);
   //  original->SetBranchAddress("doubleEGroup", &doubleEGroup);
   //  original->SetBranchAddress("doubleEPass", &doubleEPass);
   //  original->SetBranchAddress("doubleEPrescale", &doubleEPrescale);
   //  original->SetBranchAddress("doubleESingleMuGroup", &doubleESingleMuGroup);
   //  original->SetBranchAddress("doubleESingleMuPass", &doubleESingleMuPass);
   //  original->SetBranchAddress("doubleESingleMuPrescale", &doubleESingleMuPrescale);
   //  original->SetBranchAddress("doubleE_23_12Group", &doubleE_23_12Group);
   //  original->SetBranchAddress("doubleE_23_12Pass", &doubleE_23_12Pass);
   //  original->SetBranchAddress("doubleE_23_12Prescale", &doubleE_23_12Prescale);
   //  original->SetBranchAddress("doubleMuGroup", &doubleMuGroup);
   //  original->SetBranchAddress("doubleMuPass", &doubleMuPass);
   //  original->SetBranchAddress("doubleMuPrescale", &doubleMuPrescale);
   //  original->SetBranchAddress("doubleMuSingleEGroup", &doubleMuSingleEGroup);
   //  original->SetBranchAddress("doubleMuSingleEPass", &doubleMuSingleEPass);
   //  original->SetBranchAddress("doubleMuSingleEPrescale", &doubleMuSingleEPrescale);
   //  original->SetBranchAddress("doubleTau32Group", &doubleTau32Group);
   //  original->SetBranchAddress("doubleTau32Pass", &doubleTau32Pass);
   //  original->SetBranchAddress("doubleTau32Prescale", &doubleTau32Prescale);
   //  original->SetBranchAddress("doubleTau35Group", &doubleTau35Group);
   //  original->SetBranchAddress("doubleTau35Pass", &doubleTau35Pass);
   //  original->SetBranchAddress("doubleTau35Prescale", &doubleTau35Prescale);
   //  original->SetBranchAddress("doubleTau40Group", &doubleTau40Group);
   //  original->SetBranchAddress("doubleTau40Pass", &doubleTau40Pass);
   //  original->SetBranchAddress("doubleTau40Prescale", &doubleTau40Prescale);
   //  original->SetBranchAddress("doubleTauCmbIso35RegGroup", &doubleTauCmbIso35RegGroup);
   //  original->SetBranchAddress("doubleTauCmbIso35RegPass", &doubleTauCmbIso35RegPass);
   //  original->SetBranchAddress("doubleTauCmbIso35RegPrescale", &doubleTauCmbIso35RegPrescale);
   //  original->SetBranchAddress("doubleTauCmbIso40Group", &doubleTauCmbIso40Group);
   //  original->SetBranchAddress("doubleTauCmbIso40Pass", &doubleTauCmbIso40Pass);
   //  original->SetBranchAddress("doubleTauCmbIso40Prescale", &doubleTauCmbIso40Prescale);
   //  original->SetBranchAddress("doubleTauCmbIso40RegGroup", &doubleTauCmbIso40RegGroup);
   //  original->SetBranchAddress("doubleTauCmbIso40RegPass", &doubleTauCmbIso40RegPass);
   //  original->SetBranchAddress("doubleTauCmbIso40RegPrescale", &doubleTauCmbIso40RegPrescale);
   //  original->SetBranchAddress("eAbsEta", &eAbsEta);
   //  original->SetBranchAddress("eCBIDLoose", &eCBIDLoose);
   //  original->SetBranchAddress("eCBIDLooseNoIso", &eCBIDLooseNoIso);
   //  original->SetBranchAddress("eCBIDMedium", &eCBIDMedium);
   //  original->SetBranchAddress("eCBIDMediumNoIso", &eCBIDMediumNoIso);
   //  original->SetBranchAddress("eCBIDTight", &eCBIDTight);
   //  original->SetBranchAddress("eCBIDTightNoIso", &eCBIDTightNoIso);
   //  original->SetBranchAddress("eCBIDVeto", &eCBIDVeto);
   //  original->SetBranchAddress("eCBIDVetoNoIso", &eCBIDVetoNoIso);
   //  original->SetBranchAddress("eChargeIdLoose", &eChargeIdLoose);
   //  original->SetBranchAddress("eChargeIdMed", &eChargeIdMed);
   //  original->SetBranchAddress("eChargeIdTight", &eChargeIdTight);
   //  original->SetBranchAddress("eComesFromHiggs", &eComesFromHiggs);
   //  original->SetBranchAddress("eDPhiToPfMet_ElectronEnDown", &eDPhiToPfMet_ElectronEnDown);
   //  original->SetBranchAddress("eDPhiToPfMet_ElectronEnUp", &eDPhiToPfMet_ElectronEnUp);
   //  original->SetBranchAddress("eDPhiToPfMet_JetEnDown", &eDPhiToPfMet_JetEnDown);
   //  original->SetBranchAddress("eDPhiToPfMet_JetEnUp", &eDPhiToPfMet_JetEnUp);
   //  original->SetBranchAddress("eDPhiToPfMet_JetResDown", &eDPhiToPfMet_JetResDown);
   //  original->SetBranchAddress("eDPhiToPfMet_JetResUp", &eDPhiToPfMet_JetResUp);
   //  original->SetBranchAddress("eDPhiToPfMet_MuonEnDown", &eDPhiToPfMet_MuonEnDown);
   //  original->SetBranchAddress("eDPhiToPfMet_MuonEnUp", &eDPhiToPfMet_MuonEnUp);
   //  original->SetBranchAddress("eDPhiToPfMet_PhotonEnDown", &eDPhiToPfMet_PhotonEnDown);
   //  original->SetBranchAddress("eDPhiToPfMet_PhotonEnUp", &eDPhiToPfMet_PhotonEnUp);
   //  original->SetBranchAddress("eDPhiToPfMet_TauEnDown", &eDPhiToPfMet_TauEnDown);
   //  original->SetBranchAddress("eDPhiToPfMet_TauEnUp", &eDPhiToPfMet_TauEnUp);
   //  original->SetBranchAddress("eDPhiToPfMet_UnclusteredEnDown", &eDPhiToPfMet_UnclusteredEnDown);
   //  original->SetBranchAddress("eDPhiToPfMet_UnclusteredEnUp", &eDPhiToPfMet_UnclusteredEnUp);
   //  original->SetBranchAddress("eE1x5", &eE1x5);
   //  original->SetBranchAddress("eE2x5Max", &eE2x5Max);
   //  original->SetBranchAddress("eE5x5", &eE5x5);
   //  original->SetBranchAddress("eEcalIsoDR03", &eEcalIsoDR03);
   //  original->SetBranchAddress("eEffectiveArea2012Data", &eEffectiveArea2012Data);
   //  original->SetBranchAddress("eEffectiveAreaSpring15", &eEffectiveAreaSpring15);
   //  original->SetBranchAddress("eEnergyError", &eEnergyError);
   //  original->SetBranchAddress("eErsatzGenEta", &eErsatzGenEta);
   //  original->SetBranchAddress("eErsatzGenM", &eErsatzGenM);
   //  original->SetBranchAddress("eErsatzGenPhi", &eErsatzGenPhi);
   //  original->SetBranchAddress("eErsatzGenpT", &eErsatzGenpT);
   //  original->SetBranchAddress("eErsatzGenpX", &eErsatzGenpX);
   //  original->SetBranchAddress("eErsatzGenpY", &eErsatzGenpY);
   //  original->SetBranchAddress("eErsatzVispX", &eErsatzVispX);
   //  original->SetBranchAddress("eErsatzVispY", &eErsatzVispY);
   //  original->SetBranchAddress("eEta_ElectronEnDown", &eEta_ElectronEnDown);
   //  original->SetBranchAddress("eEta_ElectronEnUp", &eEta_ElectronEnUp);
   //  original->SetBranchAddress("eGenCharge", &eGenCharge);
   //  original->SetBranchAddress("eGenDirectPromptTauDecay", &eGenDirectPromptTauDecay);
   //  original->SetBranchAddress("eGenEnergy", &eGenEnergy);
   //  original->SetBranchAddress("eGenEta", &eGenEta);
   //  original->SetBranchAddress("eGenIsPrompt", &eGenIsPrompt);
   //  original->SetBranchAddress("eGenMotherPdgId", &eGenMotherPdgId);
   //  original->SetBranchAddress("eGenParticle", &eGenParticle);
   //  original->SetBranchAddress("eGenPhi", &eGenPhi);
   //  original->SetBranchAddress("eGenPrompt", &eGenPrompt);
   //  original->SetBranchAddress("eGenPromptTauDecay", &eGenPromptTauDecay);
   //  original->SetBranchAddress("eGenPt", &eGenPt);
   //  original->SetBranchAddress("eGenTauDecay", &eGenTauDecay);
   //  original->SetBranchAddress("eGenVZ", &eGenVZ);
   //  original->SetBranchAddress("eGenVtxPVMatch", &eGenVtxPVMatch);
   //  original->SetBranchAddress("eHadronicDepth1OverEm", &eHadronicDepth1OverEm);
   //  original->SetBranchAddress("eHadronicDepth2OverEm", &eHadronicDepth2OverEm);
   //  original->SetBranchAddress("eHadronicOverEM", &eHadronicOverEM);
   //  original->SetBranchAddress("eHcalIsoDR03", &eHcalIsoDR03);
   //  original->SetBranchAddress("eIP3D", &eIP3D);
   //  original->SetBranchAddress("eIP3DErr", &eIP3DErr);
   //  original->SetBranchAddress("eJetArea", &eJetArea);
   //  original->SetBranchAddress("eJetBtag", &eJetBtag);
   //  original->SetBranchAddress("eJetEtaEtaMoment", &eJetEtaEtaMoment);
   //  original->SetBranchAddress("eJetEtaPhiMoment", &eJetEtaPhiMoment);
   //  original->SetBranchAddress("eJetEtaPhiSpread", &eJetEtaPhiSpread);
   //  original->SetBranchAddress("eJetHadronFlavour", &eJetHadronFlavour);
   //  original->SetBranchAddress("eJetPFCISVBtag", &eJetPFCISVBtag);
   //  original->SetBranchAddress("eJetPartonFlavour", &eJetPartonFlavour);
   //  original->SetBranchAddress("eJetPhiPhiMoment", &eJetPhiPhiMoment);
   //  original->SetBranchAddress("eJetPt", &eJetPt);
   //  original->SetBranchAddress("eLowestMll", &eLowestMll);
   //  original->SetBranchAddress("eMVANonTrigCategory", &eMVANonTrigCategory);
   //  original->SetBranchAddress("eMVANonTrigID", &eMVANonTrigID);
   //  original->SetBranchAddress("eMVANonTrigWP90", &eMVANonTrigWP90);
   //  original->SetBranchAddress("eMVATrigCategory", &eMVATrigCategory);
   //  original->SetBranchAddress("eMVATrigID", &eMVATrigID);
   //  original->SetBranchAddress("eMVATrigWP80", &eMVATrigWP80);
   //  original->SetBranchAddress("eMVATrigWP90", &eMVATrigWP90);
   //  original->SetBranchAddress("eMatchesDoubleE", &eMatchesDoubleE);
   //  original->SetBranchAddress("eMatchesDoubleESingleMu", &eMatchesDoubleESingleMu);
   //  original->SetBranchAddress("eMatchesDoubleMuSingleE", &eMatchesDoubleMuSingleE);
   //  original->SetBranchAddress("eMatchesEle115Filter", &eMatchesEle115Filter);
   //  original->SetBranchAddress("eMatchesEle115Path", &eMatchesEle115Path);
   //  original->SetBranchAddress("eMatchesEle24Tau20Filter", &eMatchesEle24Tau20Filter);
   //  original->SetBranchAddress("eMatchesEle24Tau20Path", &eMatchesEle24Tau20Path);
   //  original->SetBranchAddress("eMatchesEle24Tau20sL1Filter", &eMatchesEle24Tau20sL1Filter);
   //  original->SetBranchAddress("eMatchesEle24Tau20sL1Path", &eMatchesEle24Tau20sL1Path);
   //  original->SetBranchAddress("eMatchesEle24Tau30Filter", &eMatchesEle24Tau30Filter);
   //  original->SetBranchAddress("eMatchesEle24Tau30Path", &eMatchesEle24Tau30Path);
   //  original->SetBranchAddress("eMatchesEle25LooseFilter", &eMatchesEle25LooseFilter);
   //  original->SetBranchAddress("eMatchesEle25eta2p1TightFilter", &eMatchesEle25eta2p1TightFilter);
   //  original->SetBranchAddress("eMatchesEle25eta2p1TightPath", &eMatchesEle25eta2p1TightPath);
   //  original->SetBranchAddress("eMatchesEle27TightFilter", &eMatchesEle27TightFilter);
   //  original->SetBranchAddress("eMatchesEle27TightPath", &eMatchesEle27TightPath);
   //  original->SetBranchAddress("eMatchesEle27eta2p1LooseFilter", &eMatchesEle27eta2p1LooseFilter);
   //  original->SetBranchAddress("eMatchesEle27eta2p1LoosePath", &eMatchesEle27eta2p1LoosePath);
   //  original->SetBranchAddress("eMatchesEle45L1JetTauPath", &eMatchesEle45L1JetTauPath);
   //  original->SetBranchAddress("eMatchesEle45LooseL1JetTauFilter", &eMatchesEle45LooseL1JetTauFilter);
   //  original->SetBranchAddress("eMatchesMu23Ele12DZFilter", &eMatchesMu23Ele12DZFilter);
   //  original->SetBranchAddress("eMatchesMu23Ele12DZPath", &eMatchesMu23Ele12DZPath);
   //  original->SetBranchAddress("eMatchesMu23Ele12Filter", &eMatchesMu23Ele12Filter);
   //  original->SetBranchAddress("eMatchesMu23Ele12Path", &eMatchesMu23Ele12Path);
   //  original->SetBranchAddress("eMatchesMu23Ele8DZFilter", &eMatchesMu23Ele8DZFilter);
   //  original->SetBranchAddress("eMatchesMu23Ele8DZPath", &eMatchesMu23Ele8DZPath);
   //  original->SetBranchAddress("eMatchesMu23Ele8Filter", &eMatchesMu23Ele8Filter);
   //  original->SetBranchAddress("eMatchesMu23Ele8Path", &eMatchesMu23Ele8Path);
   //  original->SetBranchAddress("eMatchesMu8Ele23DZFilter", &eMatchesMu8Ele23DZFilter);
   //  original->SetBranchAddress("eMatchesMu8Ele23DZPath", &eMatchesMu8Ele23DZPath);
   //  original->SetBranchAddress("eMatchesMu8Ele23Filter", &eMatchesMu8Ele23Filter);
   //  original->SetBranchAddress("eMatchesMu8Ele23Path", &eMatchesMu8Ele23Path);
   //  original->SetBranchAddress("eMatchesSingleE", &eMatchesSingleE);
   //  original->SetBranchAddress("eMatchesSingleESingleMu", &eMatchesSingleESingleMu);
   //  original->SetBranchAddress("eMatchesSingleE_leg1", &eMatchesSingleE_leg1);
   //  original->SetBranchAddress("eMatchesSingleE_leg2", &eMatchesSingleE_leg2);
   //  original->SetBranchAddress("eMatchesSingleMuSingleE", &eMatchesSingleMuSingleE);
   //  original->SetBranchAddress("eMatchesTripleE", &eMatchesTripleE);
   //  original->SetBranchAddress("eMtToPfMet_ElectronEnDown", &eMtToPfMet_ElectronEnDown);
   //  original->SetBranchAddress("eMtToPfMet_ElectronEnUp", &eMtToPfMet_ElectronEnUp);
   //  original->SetBranchAddress("eMtToPfMet_JetEnDown", &eMtToPfMet_JetEnDown);
   //  original->SetBranchAddress("eMtToPfMet_JetEnUp", &eMtToPfMet_JetEnUp);
   //  original->SetBranchAddress("eMtToPfMet_JetResDown", &eMtToPfMet_JetResDown);
   //  original->SetBranchAddress("eMtToPfMet_JetResUp", &eMtToPfMet_JetResUp);
   //  original->SetBranchAddress("eMtToPfMet_MuonEnDown", &eMtToPfMet_MuonEnDown);
   //  original->SetBranchAddress("eMtToPfMet_MuonEnUp", &eMtToPfMet_MuonEnUp);
   //  original->SetBranchAddress("eMtToPfMet_PhotonEnDown", &eMtToPfMet_PhotonEnDown);
   //  original->SetBranchAddress("eMtToPfMet_PhotonEnUp", &eMtToPfMet_PhotonEnUp);
   //  original->SetBranchAddress("eMtToPfMet_Raw", &eMtToPfMet_Raw);
   //  original->SetBranchAddress("eMtToPfMet_TauEnDown", &eMtToPfMet_TauEnDown);
   //  original->SetBranchAddress("eMtToPfMet_TauEnUp", &eMtToPfMet_TauEnUp);
   //  original->SetBranchAddress("eMtToPfMet_UnclusteredEnDown", &eMtToPfMet_UnclusteredEnDown);
   //  original->SetBranchAddress("eMtToPfMet_UnclusteredEnUp", &eMtToPfMet_UnclusteredEnUp);
   //  original->SetBranchAddress("eNearMuonVeto", &eNearMuonVeto);
   //  original->SetBranchAddress("eNearestMuonDR", &eNearestMuonDR);
   //  original->SetBranchAddress("eNearestZMass", &eNearestZMass);
   //  original->SetBranchAddress("ePFChargedIso", &ePFChargedIso);
   //  original->SetBranchAddress("ePFNeutralIso", &ePFNeutralIso);
   //  original->SetBranchAddress("ePFPUChargedIso", &ePFPUChargedIso);
   //  original->SetBranchAddress("ePFPhotonIso", &ePFPhotonIso);
   //  original->SetBranchAddress("ePhi_ElectronEnDown", &ePhi_ElectronEnDown);
   //  original->SetBranchAddress("ePhi_ElectronEnUp", &ePhi_ElectronEnUp);
   //  original->SetBranchAddress("ePt_ElectronEnDown", &ePt_ElectronEnDown);
   //  original->SetBranchAddress("ePt_ElectronEnUp", &ePt_ElectronEnUp);
   //  original->SetBranchAddress("eRank", &eRank);
   //  original->SetBranchAddress("eRelIso", &eRelIso);
   //  original->SetBranchAddress("eRelPFIsoDB", &eRelPFIsoDB);
   //  original->SetBranchAddress("eRelPFIsoRho", &eRelPFIsoRho);
   //  original->SetBranchAddress("eRho", &eRho);
   //  original->SetBranchAddress("eSCEnergy", &eSCEnergy);
   //  original->SetBranchAddress("eSCEta", &eSCEta);
   //  original->SetBranchAddress("eSCEtaWidth", &eSCEtaWidth);
   //  original->SetBranchAddress("eSCPhi", &eSCPhi);
   //  original->SetBranchAddress("eSCPhiWidth", &eSCPhiWidth);
   //  original->SetBranchAddress("eSCPreshowerEnergy", &eSCPreshowerEnergy);
   //  original->SetBranchAddress("eSCRawEnergy", &eSCRawEnergy);
   //  original->SetBranchAddress("eSIP2D", &eSIP2D);
   //  original->SetBranchAddress("eSIP3D", &eSIP3D);
   //  original->SetBranchAddress("eSigmaIEtaIEta", &eSigmaIEtaIEta);
   //  original->SetBranchAddress("eTrkIsoDR03", &eTrkIsoDR03);
   //  original->SetBranchAddress("eVZ", &eVZ);
   //  original->SetBranchAddress("eVetoMVAIso", &eVetoMVAIso);
   //  original->SetBranchAddress("eVetoMVAIsoVtx", &eVetoMVAIsoVtx);
   //  original->SetBranchAddress("eVetoZTTp001dxyz", &eVetoZTTp001dxyz);
   //  original->SetBranchAddress("eWWLoose", &eWWLoose);
   //  original->SetBranchAddress("edeltaEtaSuperClusterTrackAtVtx", &edeltaEtaSuperClusterTrackAtVtx);
   //  original->SetBranchAddress("edeltaPhiSuperClusterTrackAtVtx", &edeltaPhiSuperClusterTrackAtVtx);
   //  original->SetBranchAddress("eeSuperClusterOverP", &eeSuperClusterOverP);
   //  original->SetBranchAddress("eecalEnergy", &eecalEnergy);
   //  original->SetBranchAddress("efBrem", &efBrem);
   //  original->SetBranchAddress("etrackMomentumAtVtxP", &etrackMomentumAtVtxP);
   //  original->SetBranchAddress("genEta", &genEta);
   //  original->SetBranchAddress("genHTT", &genHTT);
   //  // original->SetBranchAddress("genM", &genM);
   //  // original->SetBranchAddress("genMass", &genMass);
   //  // original->SetBranchAddress("genPhi", &genPhi);
   //  // original->SetBranchAddress("genpT", &genpT);
   //  // original->SetBranchAddress("genpX", &genpX);
   //  // original->SetBranchAddress("genpY", &genpY);
   //  original->SetBranchAddress("isGtautau", &isGtautau);
   //  original->SetBranchAddress("isWenu", &isWenu);
   //  original->SetBranchAddress("isWmunu", &isWmunu);
   //  original->SetBranchAddress("isWtaunu", &isWtaunu);
   //  original->SetBranchAddress("isZee", &isZee);
   //  original->SetBranchAddress("isZmumu", &isZmumu);
   //  original->SetBranchAddress("isdata", &isdata);
   //  original->SetBranchAddress("j1hadronflavor", &j1hadronflavor);
   //  original->SetBranchAddress("j1partonflavor", &j1partonflavor);
   //
   //
   //
   //  original->SetBranchAddress("j1ptDown", &j1ptDown);
   //  original->SetBranchAddress("j1ptUp", &j1ptUp);
   //  original->SetBranchAddress("j1pu", &j1pu);
   //  original->SetBranchAddress("j1rawf", &j1rawf);
   //  original->SetBranchAddress("j2hadronflavor", &j2hadronflavor);
   //  original->SetBranchAddress("j2partonflavor", &j2partonflavor);
   //  original->SetBranchAddress("j2ptDown", &j2ptDown);
   //  original->SetBranchAddress("j2ptUp", &j2ptUp);
   //  original->SetBranchAddress("j2pu", &j2pu);
   //  original->SetBranchAddress("j2rawf", &j2rawf);
   //  original->SetBranchAddress("jb1csv_CSVL", &jb1csv_CSVL);
   //  original->SetBranchAddress("jb1eta_CSVL", &jb1eta_CSVL);
   //  original->SetBranchAddress("jb1hadronflavor", &jb1hadronflavor);
   //  original->SetBranchAddress("jb1hadronflavor_CSVL", &jb1hadronflavor_CSVL);
   //  original->SetBranchAddress("jb1partonflavor", &jb1partonflavor);
   //  original->SetBranchAddress("jb1partonflavor_CSVL", &jb1partonflavor_CSVL);
   //  original->SetBranchAddress("jb1phi_CSVL", &jb1phi_CSVL);
   //  original->SetBranchAddress("jb1ptDown", &jb1ptDown);
   //  original->SetBranchAddress("jb1ptDown_CSVL", &jb1ptDown_CSVL);
   //  original->SetBranchAddress("jb1ptUp", &jb1ptUp);
   //  original->SetBranchAddress("jb1ptUp_CSVL", &jb1ptUp_CSVL);
   //  original->SetBranchAddress("jb1pt_CSVL", &jb1pt_CSVL);
   //  original->SetBranchAddress("jb1pu", &jb1pu);
   //  original->SetBranchAddress("jb1pu_CSVL", &jb1pu_CSVL);
   //  original->SetBranchAddress("jb1rawf", &jb1rawf);
   //  original->SetBranchAddress("jb1rawf_CSVL", &jb1rawf_CSVL);
   //  original->SetBranchAddress("jb2csv_CSVL", &jb2csv_CSVL);
   //  original->SetBranchAddress("jb2eta_CSVL", &jb2eta_CSVL);
   //  original->SetBranchAddress("jb2hadronflavor", &jb2hadronflavor);
   //  original->SetBranchAddress("jb2hadronflavor_CSVL", &jb2hadronflavor_CSVL);
   //  original->SetBranchAddress("jb2partonflavor", &jb2partonflavor);
   //  original->SetBranchAddress("jb2partonflavor_CSVL", &jb2partonflavor_CSVL);
   //  original->SetBranchAddress("jb2phi_CSVL", &jb2phi_CSVL);
   //  original->SetBranchAddress("jb2ptDown", &jb2ptDown);
   //  original->SetBranchAddress("jb2ptDown_CSVL", &jb2ptDown_CSVL);
   //  original->SetBranchAddress("jb2ptUp", &jb2ptUp);
   //  original->SetBranchAddress("jb2ptUp_CSVL", &jb2ptUp_CSVL);
   //  original->SetBranchAddress("jb2pt_CSVL", &jb2pt_CSVL);
   //  original->SetBranchAddress("jb2pu", &jb2pu);
   //  original->SetBranchAddress("jb2pu_CSVL", &jb2pu_CSVL);
   //  original->SetBranchAddress("jb2rawf", &jb2rawf);
   //
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteFlavMapDown", &jetVeto30_JetAbsoluteFlavMapDown);
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteFlavMapUp", &jetVeto30_JetAbsoluteFlavMapUp);
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteMPFBiasDown", &jetVeto30_JetAbsoluteMPFBiasDown);
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteMPFBiasUp", &jetVeto30_JetAbsoluteMPFBiasUp);
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteScaleDown", &jetVeto30_JetAbsoluteScaleDown);
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteScaleUp", &jetVeto30_JetAbsoluteScaleUp);
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteStatDown", &jetVeto30_JetAbsoluteStatDown);
   //  original->SetBranchAddress("jetVeto30_JetAbsoluteStatUp", &jetVeto30_JetAbsoluteStatUp);
   //  original->SetBranchAddress("jetVeto30_JetClosureDown", &jetVeto30_JetClosureDown);
   //  original->SetBranchAddress("jetVeto30_JetClosureUp", &jetVeto30_JetClosureUp);
   //  original->SetBranchAddress("jb2rawf_CSVL", &jb2rawf_CSVL);
   //
   //  original->SetBranchAddress("jetVeto30_JetFlavorQCDDown", &jetVeto30_JetFlavorQCDDown);
   //  original->SetBranchAddress("jetVeto30_JetFlavorQCDUp", &jetVeto30_JetFlavorQCDUp);
   //  original->SetBranchAddress("jetVeto30_JetFragmentationDown", &jetVeto30_JetFragmentationDown);
   //  original->SetBranchAddress("jetVeto30_JetFragmentationUp", &jetVeto30_JetFragmentationUp);
   //  original->SetBranchAddress("jetVeto30_JetPileUpDataMCDown", &jetVeto30_JetPileUpDataMCDown);
   //  original->SetBranchAddress("jetVeto30_JetPileUpDataMCUp", &jetVeto30_JetPileUpDataMCUp);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtBBDown", &jetVeto30_JetPileUpPtBBDown);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtBBUp", &jetVeto30_JetPileUpPtBBUp);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtEC1Down", &jetVeto30_JetPileUpPtEC1Down);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtEC1Up", &jetVeto30_JetPileUpPtEC1Up);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtEC2Down", &jetVeto30_JetPileUpPtEC2Down);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtEC2Up", &jetVeto30_JetPileUpPtEC2Up);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtHFDown", &jetVeto30_JetPileUpPtHFDown);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtHFUp", &jetVeto30_JetPileUpPtHFUp);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtRefDown", &jetVeto30_JetPileUpPtRefDown);
   //  original->SetBranchAddress("jetVeto30_JetPileUpPtRefUp", &jetVeto30_JetPileUpPtRefUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativeBalDown", &jetVeto30_JetRelativeBalDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativeBalUp", &jetVeto30_JetRelativeBalUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativeFSRDown", &jetVeto30_JetRelativeFSRDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativeFSRUp", &jetVeto30_JetRelativeFSRUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativeJEREC1Down", &jetVeto30_JetRelativeJEREC1Down);
   //  original->SetBranchAddress("jetVeto30_JetRelativeJEREC1Up", &jetVeto30_JetRelativeJEREC1Up);
   //  original->SetBranchAddress("jetVeto30_JetRelativeJEREC2Down", &jetVeto30_JetRelativeJEREC2Down);
   //  original->SetBranchAddress("jetVeto30_JetRelativeJEREC2Up", &jetVeto30_JetRelativeJEREC2Up);
   //  original->SetBranchAddress("jetVeto30_JetRelativeJERHFDown", &jetVeto30_JetRelativeJERHFDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativeJERHFUp", &jetVeto30_JetRelativeJERHFUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtBBDown", &jetVeto30_JetRelativePtBBDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtBBUp", &jetVeto30_JetRelativePtBBUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtEC1Down", &jetVeto30_JetRelativePtEC1Down);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtEC1Up", &jetVeto30_JetRelativePtEC1Up);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtEC2Down", &jetVeto30_JetRelativePtEC2Down);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtEC2Up", &jetVeto30_JetRelativePtEC2Up);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtHFDown", &jetVeto30_JetRelativePtHFDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativePtHFUp", &jetVeto30_JetRelativePtHFUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativeStatECDown", &jetVeto30_JetRelativeStatECDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativeStatECUp", &jetVeto30_JetRelativeStatECUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativeStatFSRDown", &jetVeto30_JetRelativeStatFSRDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativeStatFSRUp", &jetVeto30_JetRelativeStatFSRUp);
   //  original->SetBranchAddress("jetVeto30_JetRelativeStatHFDown", &jetVeto30_JetRelativeStatHFDown);
   //  original->SetBranchAddress("jetVeto30_JetRelativeStatHFUp", &jetVeto30_JetRelativeStatHFUp);
   //  original->SetBranchAddress("jetVeto30_JetSinglePionECALDown", &jetVeto30_JetSinglePionECALDown);
   //  original->SetBranchAddress("jetVeto30_JetSinglePionECALUp", &jetVeto30_JetSinglePionECALUp);
   //  original->SetBranchAddress("jetVeto30_JetSinglePionHCALDown", &jetVeto30_JetSinglePionHCALDown);
   //  original->SetBranchAddress("jetVeto30_JetSinglePionHCALUp", &jetVeto30_JetSinglePionHCALUp);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalAbsoluteDown", &jetVeto30_JetSubTotalAbsoluteDown);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalAbsoluteUp", &jetVeto30_JetSubTotalAbsoluteUp);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalMCDown", &jetVeto30_JetSubTotalMCDown);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalMCUp", &jetVeto30_JetSubTotalMCUp);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalPileUpDown", &jetVeto30_JetSubTotalPileUpDown);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalPileUpUp", &jetVeto30_JetSubTotalPileUpUp);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalPtDown", &jetVeto30_JetSubTotalPtDown);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalPtUp", &jetVeto30_JetSubTotalPtUp);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalRelativeDown", &jetVeto30_JetSubTotalRelativeDown);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalRelativeUp", &jetVeto30_JetSubTotalRelativeUp);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalScaleDown", &jetVeto30_JetSubTotalScaleDown);
   //  original->SetBranchAddress("jetVeto30_JetSubTotalScaleUp", &jetVeto30_JetSubTotalScaleUp);
   //  original->SetBranchAddress("jetVeto30_JetTimePtEtaDown", &jetVeto30_JetTimePtEtaDown);
   //  original->SetBranchAddress("jetVeto30_JetTimePtEtaUp", &jetVeto30_JetTimePtEtaUp);
   //  original->SetBranchAddress("jetVeto30_JetTotalDown", &jetVeto30_JetTotalDown);
   //  original->SetBranchAddress("jetVeto30_JetTotalUp", &jetVeto30_JetTotalUp);
   //  original->SetBranchAddress("muGlbIsoVetoPt10", &muGlbIsoVetoPt10);
   //  original->SetBranchAddress("muVetoPt15IsoIdVtx", &muVetoPt15IsoIdVtx);
   //  original->SetBranchAddress("muVetoPt5", &muVetoPt5);
   //  original->SetBranchAddress("muVetoPt5IsoIdVtx", &muVetoPt5IsoIdVtx);
   //  original->SetBranchAddress("muVetoZTTp001dxyz", &muVetoZTTp001dxyz);
   //  original->SetBranchAddress("processID", &processID);
   //  original->SetBranchAddress("puppiMetEt", &puppiMetEt);
   //  original->SetBranchAddress("puppiMetPhi", &puppiMetPhi);
   //  original->SetBranchAddress("pvChi2", &pvChi2);
   //  original->SetBranchAddress("pvDX", &pvDX);
   //  original->SetBranchAddress("pvDY", &pvDY);
   //  original->SetBranchAddress("pvDZ", &pvDZ);
   //  original->SetBranchAddress("pvIsFake", &pvIsFake);
   //  original->SetBranchAddress("pvIsValid", &pvIsValid);
   //  original->SetBranchAddress("pvNormChi2", &pvNormChi2);
   //  original->SetBranchAddress("pvRho", &pvRho);
   //  original->SetBranchAddress("pvX", &pvX);
   //  original->SetBranchAddress("pvY", &pvY);
   //  original->SetBranchAddress("pvZ", &pvZ);
   //  original->SetBranchAddress("pvndof", &pvndof);
   //  original->SetBranchAddress("raw_pfMetEt", &raw_pfMetEt);
   //  original->SetBranchAddress("raw_pfMetPhi", &raw_pfMetPhi);
   //  original->SetBranchAddress("recoilDaught", &recoilDaught);
   //  original->SetBranchAddress("recoilWithMet", &recoilWithMet);
   //  original->SetBranchAddress("singleE17SingleMu8Group", &singleE17SingleMu8Group);
   //  original->SetBranchAddress("singleE17SingleMu8Pass", &singleE17SingleMu8Pass);
   //  original->SetBranchAddress("singleE17SingleMu8Prescale", &singleE17SingleMu8Prescale);
   //  original->SetBranchAddress("singleE20SingleTau28Group", &singleE20SingleTau28Group);
   //  original->SetBranchAddress("singleE20SingleTau28Pass", &singleE20SingleTau28Pass);
   //  original->SetBranchAddress("singleE20SingleTau28Prescale", &singleE20SingleTau28Prescale);
   //  original->SetBranchAddress("singleE22SingleTau20SingleL1Group", &singleE22SingleTau20SingleL1Group);
   //  original->SetBranchAddress("singleE22SingleTau20SingleL1Pass", &singleE22SingleTau20SingleL1Pass);
   //  original->SetBranchAddress("singleE22SingleTau20SingleL1Prescale", &singleE22SingleTau20SingleL1Prescale);
   //  original->SetBranchAddress("singleE22SingleTau29Group", &singleE22SingleTau29Group);
   //  original->SetBranchAddress("singleE22SingleTau29Pass", &singleE22SingleTau29Pass);
   //  original->SetBranchAddress("singleE22SingleTau29Prescale", &singleE22SingleTau29Prescale);
   //  original->SetBranchAddress("singleE23SingleMu8Group", &singleE23SingleMu8Group);
   //  original->SetBranchAddress("singleE23SingleMu8Pass", &singleE23SingleMu8Pass);
   //  original->SetBranchAddress("singleE23SingleMu8Prescale", &singleE23SingleMu8Prescale);
   //  original->SetBranchAddress("singleE24SingleTau20Group", &singleE24SingleTau20Group);
   //  original->SetBranchAddress("singleE24SingleTau20Pass", &singleE24SingleTau20Pass);
   //  original->SetBranchAddress("singleE24SingleTau20Prescale", &singleE24SingleTau20Prescale);
   //  original->SetBranchAddress("singleE24SingleTau20SingleL1Group", &singleE24SingleTau20SingleL1Group);
   //  original->SetBranchAddress("singleE24SingleTau20SingleL1Pass", &singleE24SingleTau20SingleL1Pass);
   //  original->SetBranchAddress("singleE24SingleTau20SingleL1Prescale", &singleE24SingleTau20SingleL1Prescale);
   //  original->SetBranchAddress("singleE24SingleTau30Group", &singleE24SingleTau30Group);
   //  original->SetBranchAddress("singleE24SingleTau30Pass", &singleE24SingleTau30Pass);
   //  original->SetBranchAddress("singleE24SingleTau30Prescale", &singleE24SingleTau30Prescale);
   //  original->SetBranchAddress("singleE25eta2p1TightGroup", &singleE25eta2p1TightGroup);
   //  original->SetBranchAddress("singleE25eta2p1TightPrescale", &singleE25eta2p1TightPrescale);
   //  original->SetBranchAddress("singleE27SingleTau20SingleL1Group", &singleE27SingleTau20SingleL1Group);
   //  original->SetBranchAddress("singleE27SingleTau20SingleL1Pass", &singleE27SingleTau20SingleL1Pass);
   //  original->SetBranchAddress("singleE27SingleTau20SingleL1Prescale", &singleE27SingleTau20SingleL1Prescale);
   //  original->SetBranchAddress("singleE27TightGroup", &singleE27TightGroup);
   //  original->SetBranchAddress("singleE27TightPrescale", &singleE27TightPrescale);
   //  original->SetBranchAddress("singleE27eta2p1LooseGroup", &singleE27eta2p1LooseGroup);
   //  original->SetBranchAddress("singleE27eta2p1LoosePass", &singleE27eta2p1LoosePass);
   //  original->SetBranchAddress("singleE27eta2p1LoosePrescale", &singleE27eta2p1LoosePrescale);
   //  original->SetBranchAddress("singleE27eta2p1TightGroup", &singleE27eta2p1TightGroup);
   //  original->SetBranchAddress("singleE27eta2p1TightPass", &singleE27eta2p1TightPass);
   //  original->SetBranchAddress("singleE27eta2p1TightPrescale", &singleE27eta2p1TightPrescale);
   //  original->SetBranchAddress("singleE32SingleTau20SingleL1Group", &singleE32SingleTau20SingleL1Group);
   //  original->SetBranchAddress("singleE32SingleTau20SingleL1Pass", &singleE32SingleTau20SingleL1Pass);
   //  original->SetBranchAddress("singleE32SingleTau20SingleL1Prescale", &singleE32SingleTau20SingleL1Prescale);
   //  original->SetBranchAddress("singleE36SingleTau30Group", &singleE36SingleTau30Group);
   //  original->SetBranchAddress("singleE36SingleTau30Pass", &singleE36SingleTau30Pass);
   //  original->SetBranchAddress("singleE36SingleTau30Prescale", &singleE36SingleTau30Prescale);
   //  original->SetBranchAddress("singleESingleMuGroup", &singleESingleMuGroup);
   //  original->SetBranchAddress("singleESingleMuPass", &singleESingleMuPass);
   //  original->SetBranchAddress("singleESingleMuPrescale", &singleESingleMuPrescale);
   //  original->SetBranchAddress("singleE_leg1Group", &singleE_leg1Group);
   //  original->SetBranchAddress("singleE_leg1Pass", &singleE_leg1Pass);
   //  original->SetBranchAddress("singleE_leg1Prescale", &singleE_leg1Prescale);
   //  original->SetBranchAddress("singleE_leg2Group", &singleE_leg2Group);
   //  original->SetBranchAddress("singleE_leg2Pass", &singleE_leg2Pass);
   //  original->SetBranchAddress("singleE_leg2Prescale", &singleE_leg2Prescale);
   //  original->SetBranchAddress("singleIsoMu20Group", &singleIsoMu20Group);
   //  original->SetBranchAddress("singleIsoMu20Pass", &singleIsoMu20Pass);
   //  original->SetBranchAddress("singleIsoMu20Prescale", &singleIsoMu20Prescale);
   //  original->SetBranchAddress("singleIsoMu22Group", &singleIsoMu22Group);
   //  original->SetBranchAddress("singleIsoMu22Pass", &singleIsoMu22Pass);
   //  original->SetBranchAddress("singleIsoMu22Prescale", &singleIsoMu22Prescale);
   //  original->SetBranchAddress("singleIsoMu22eta2p1Group", &singleIsoMu22eta2p1Group);
   //  original->SetBranchAddress("singleIsoMu22eta2p1Pass", &singleIsoMu22eta2p1Pass);
   //  original->SetBranchAddress("singleIsoMu22eta2p1Prescale", &singleIsoMu22eta2p1Prescale);
   //  original->SetBranchAddress("singleIsoMu24Group", &singleIsoMu24Group);
   //  original->SetBranchAddress("singleIsoMu24Pass", &singleIsoMu24Pass);
   //  original->SetBranchAddress("singleIsoMu24Prescale", &singleIsoMu24Prescale);
   //  original->SetBranchAddress("singleIsoMu24eta2p1Group", &singleIsoMu24eta2p1Group);
   //  original->SetBranchAddress("singleIsoMu24eta2p1Pass", &singleIsoMu24eta2p1Pass);
   //  original->SetBranchAddress("singleIsoMu24eta2p1Prescale", &singleIsoMu24eta2p1Prescale);
   //  original->SetBranchAddress("singleIsoMu27Group", &singleIsoMu27Group);
   //  original->SetBranchAddress("singleIsoMu27Pass", &singleIsoMu27Pass);
   //  original->SetBranchAddress("singleIsoMu27Prescale", &singleIsoMu27Prescale);
   //  original->SetBranchAddress("singleIsoTkMu20Group", &singleIsoTkMu20Group);
   //  original->SetBranchAddress("singleIsoTkMu20Pass", &singleIsoTkMu20Pass);
   //  original->SetBranchAddress("singleIsoTkMu20Prescale", &singleIsoTkMu20Prescale);
   //  original->SetBranchAddress("singleIsoTkMu22Group", &singleIsoTkMu22Group);
   //  original->SetBranchAddress("singleIsoTkMu22Pass", &singleIsoTkMu22Pass);
   //  original->SetBranchAddress("singleIsoTkMu22Prescale", &singleIsoTkMu22Prescale);
   //  original->SetBranchAddress("singleIsoTkMu22eta2p1Group", &singleIsoTkMu22eta2p1Group);
   //  original->SetBranchAddress("singleIsoTkMu22eta2p1Pass", &singleIsoTkMu22eta2p1Pass);
   //  original->SetBranchAddress("singleIsoTkMu22eta2p1Prescale", &singleIsoTkMu22eta2p1Prescale);
   //  original->SetBranchAddress("singleIsoTkMu24Group", &singleIsoTkMu24Group);
   //  original->SetBranchAddress("singleIsoTkMu24Pass", &singleIsoTkMu24Pass);
   //  original->SetBranchAddress("singleIsoTkMu24Prescale", &singleIsoTkMu24Prescale);
   //  original->SetBranchAddress("singleIsoTkMu24eta2p1Group", &singleIsoTkMu24eta2p1Group);
   //  original->SetBranchAddress("singleIsoTkMu24eta2p1Pass", &singleIsoTkMu24eta2p1Pass);
   //  original->SetBranchAddress("singleIsoTkMu24eta2p1Prescale", &singleIsoTkMu24eta2p1Prescale);
   //  original->SetBranchAddress("singleMu17SingleE12Group", &singleMu17SingleE12Group);
   //  original->SetBranchAddress("singleMu17SingleE12Pass", &singleMu17SingleE12Pass);
   //  original->SetBranchAddress("singleMu17SingleE12Prescale", &singleMu17SingleE12Prescale);
   //  original->SetBranchAddress("singleMu19eta2p1LooseTau20Group", &singleMu19eta2p1LooseTau20Group);
   //  original->SetBranchAddress("singleMu19eta2p1LooseTau20Pass", &singleMu19eta2p1LooseTau20Pass);
   //  original->SetBranchAddress("singleMu19eta2p1LooseTau20Prescale", &singleMu19eta2p1LooseTau20Prescale);
   //  original->SetBranchAddress("singleMu19eta2p1LooseTau20singleL1Group", &singleMu19eta2p1LooseTau20singleL1Group);
   //  original->SetBranchAddress("singleMu19eta2p1LooseTau20singleL1Pass", &singleMu19eta2p1LooseTau20singleL1Pass);
   //  original->SetBranchAddress("singleMu19eta2p1LooseTau20singleL1Prescale", &singleMu19eta2p1LooseTau20singleL1Prescale);
   //  original->SetBranchAddress("singleMu21eta2p1LooseTau20singleL1Group", &singleMu21eta2p1LooseTau20singleL1Group);
   //  original->SetBranchAddress("singleMu21eta2p1LooseTau20singleL1Pass", &singleMu21eta2p1LooseTau20singleL1Pass);
   //  original->SetBranchAddress("singleMu21eta2p1LooseTau20singleL1Prescale", &singleMu21eta2p1LooseTau20singleL1Prescale);
   //  original->SetBranchAddress("singleMu23SingleE12DZGroup", &singleMu23SingleE12DZGroup);
   //  original->SetBranchAddress("singleMu23SingleE12DZPass", &singleMu23SingleE12DZPass);
   //  original->SetBranchAddress("singleMu23SingleE12DZPrescale", &singleMu23SingleE12DZPrescale);
   //  original->SetBranchAddress("singleMu23SingleE12Group", &singleMu23SingleE12Group);
   //  original->SetBranchAddress("singleMu23SingleE12Pass", &singleMu23SingleE12Pass);
   //  original->SetBranchAddress("singleMu23SingleE12Prescale", &singleMu23SingleE12Prescale);
   //  original->SetBranchAddress("singleMu23SingleE8Group", &singleMu23SingleE8Group);
   //  original->SetBranchAddress("singleMu23SingleE8Pass", &singleMu23SingleE8Pass);
   //  original->SetBranchAddress("singleMu23SingleE8Prescale", &singleMu23SingleE8Prescale);
   //  original->SetBranchAddress("singleMu8SingleE23DZGroup", &singleMu8SingleE23DZGroup);
   //  original->SetBranchAddress("singleMu8SingleE23DZPass", &singleMu8SingleE23DZPass);
   //  original->SetBranchAddress("singleMu8SingleE23DZPrescale", &singleMu8SingleE23DZPrescale);
   //  original->SetBranchAddress("singleMuGroup", &singleMuGroup);
   //  original->SetBranchAddress("singleMuPass", &singleMuPass);
   //  original->SetBranchAddress("singleMuPrescale", &singleMuPrescale);
   //  original->SetBranchAddress("singleMuSingleEGroup", &singleMuSingleEGroup);
   //  original->SetBranchAddress("singleMuSingleEPrescale", &singleMuSingleEPrescale);
   //  original->SetBranchAddress("singleMu_leg1Group", &singleMu_leg1Group);
   //  original->SetBranchAddress("singleMu_leg1Pass", &singleMu_leg1Pass);
   //  original->SetBranchAddress("singleMu_leg1Prescale", &singleMu_leg1Prescale);
   //  original->SetBranchAddress("singleMu_leg1_noisoGroup", &singleMu_leg1_noisoGroup);
   //  original->SetBranchAddress("singleMu_leg1_noisoPass", &singleMu_leg1_noisoPass);
   //  original->SetBranchAddress("singleMu_leg1_noisoPrescale", &singleMu_leg1_noisoPrescale);
   //  original->SetBranchAddress("singleMu_leg2Group", &singleMu_leg2Group);
   //  original->SetBranchAddress("singleMu_leg2Pass", &singleMu_leg2Pass);
   //  original->SetBranchAddress("singleMu_leg2Prescale", &singleMu_leg2Prescale);
   //  original->SetBranchAddress("singleMu_leg2_noisoGroup", &singleMu_leg2_noisoGroup);
   //  original->SetBranchAddress("singleMu_leg2_noisoPass", &singleMu_leg2_noisoPass);
   //  original->SetBranchAddress("singleMu_leg2_noisoPrescale", &singleMu_leg2_noisoPrescale);
   //  original->SetBranchAddress("singleTau140Group", &singleTau140Group);
   //  original->SetBranchAddress("singleTau140Pass", &singleTau140Pass);
   //  original->SetBranchAddress("singleTau140Prescale", &singleTau140Prescale);
   //  original->SetBranchAddress("singleTau140Trk50Group", &singleTau140Trk50Group);
   //  original->SetBranchAddress("singleTau140Trk50Pass", &singleTau140Trk50Pass);
   //  original->SetBranchAddress("singleTau140Trk50Prescale", &singleTau140Trk50Prescale);
   //  original->SetBranchAddress("tAbsEta", &tAbsEta);
   //  original->SetBranchAddress("tChargedIsoPtSumdR03", &tChargedIsoPtSumdR03);
   //  original->SetBranchAddress("tComesFromHiggs", &tComesFromHiggs);
   //  original->SetBranchAddress("tDPhiToPfMet_ElectronEnDown", &tDPhiToPfMet_ElectronEnDown);
   //  original->SetBranchAddress("tDPhiToPfMet_ElectronEnUp", &tDPhiToPfMet_ElectronEnUp);
   //  original->SetBranchAddress("tDPhiToPfMet_JetEnDown", &tDPhiToPfMet_JetEnDown);
   //  original->SetBranchAddress("tDPhiToPfMet_JetEnUp", &tDPhiToPfMet_JetEnUp);
   //  original->SetBranchAddress("tDPhiToPfMet_JetResDown", &tDPhiToPfMet_JetResDown);
   //  original->SetBranchAddress("tDPhiToPfMet_JetResUp", &tDPhiToPfMet_JetResUp);
   //  original->SetBranchAddress("tDPhiToPfMet_MuonEnDown", &tDPhiToPfMet_MuonEnDown);
   //  original->SetBranchAddress("tDPhiToPfMet_MuonEnUp", &tDPhiToPfMet_MuonEnUp);
   //  original->SetBranchAddress("tDPhiToPfMet_PhotonEnDown", &tDPhiToPfMet_PhotonEnDown);
   //  original->SetBranchAddress("tDPhiToPfMet_PhotonEnUp", &tDPhiToPfMet_PhotonEnUp);
   //  original->SetBranchAddress("tDPhiToPfMet_TauEnDown", &tDPhiToPfMet_TauEnDown);
   //  original->SetBranchAddress("tDPhiToPfMet_TauEnUp", &tDPhiToPfMet_TauEnUp);
   //  original->SetBranchAddress("tDPhiToPfMet_UnclusteredEnDown", &tDPhiToPfMet_UnclusteredEnDown);
   //  original->SetBranchAddress("tDPhiToPfMet_UnclusteredEnUp", &tDPhiToPfMet_UnclusteredEnUp);
   //  original->SetBranchAddress("tDPhiToPfMet_type1", &tDPhiToPfMet_type1);
   //  original->SetBranchAddress("tElecOverlap", &tElecOverlap);
   //  original->SetBranchAddress("tEta", &tEta);
   //  original->SetBranchAddress("tEta_TauEnDown", &tEta_TauEnDown);
   //  original->SetBranchAddress("tEta_TauEnUp", &tEta_TauEnUp);
   //  original->SetBranchAddress("tFootprintCorrection", &tFootprintCorrection);
   //  original->SetBranchAddress("tFootprintCorrectiondR03", &tFootprintCorrectiondR03);
   //  original->SetBranchAddress("tGenCharge", &tGenCharge);
   //  original->SetBranchAddress("tGenDecayMode", &tGenDecayMode);
   //  original->SetBranchAddress("tGenEnergy", &tGenEnergy);
   //  original->SetBranchAddress("tGenEta", &tGenEta);
   //  original->SetBranchAddress("tGenIsPrompt", &tGenIsPrompt);
   //  original->SetBranchAddress("tGenJetEta", &tGenJetEta);
   //  original->SetBranchAddress("tGenJetPt", &tGenJetPt);
   //  original->SetBranchAddress("tGenMotherEnergy", &tGenMotherEnergy);
   //  original->SetBranchAddress("tGenMotherEta", &tGenMotherEta);
   //  original->SetBranchAddress("tGenMotherPdgId", &tGenMotherPdgId);
   //  original->SetBranchAddress("tGenMotherPhi", &tGenMotherPhi);
   //  original->SetBranchAddress("tGenMotherPt", &tGenMotherPt);
   //  original->SetBranchAddress("tGenPdgId", &tGenPdgId);
   //  original->SetBranchAddress("tGenPhi", &tGenPhi);
   //  original->SetBranchAddress("tGenPt", &tGenPt);
   //  original->SetBranchAddress("tGenStatus", &tGenStatus);
   //  original->SetBranchAddress("tGlobalMuonVtxOverlap", &tGlobalMuonVtxOverlap);
   //  original->SetBranchAddress("tJetArea", &tJetArea);
   //  original->SetBranchAddress("tJetBtag", &tJetBtag);
   //  original->SetBranchAddress("tJetEtaEtaMoment", &tJetEtaEtaMoment);
   //  original->SetBranchAddress("tJetEtaPhiMoment", &tJetEtaPhiMoment);
   //  original->SetBranchAddress("tJetEtaPhiSpread", &tJetEtaPhiSpread);
   //  original->SetBranchAddress("tJetHadronFlavour", &tJetHadronFlavour);
   //  original->SetBranchAddress("tJetPFCISVBtag", &tJetPFCISVBtag);
   //  original->SetBranchAddress("tJetPartonFlavour", &tJetPartonFlavour);
   //  original->SetBranchAddress("tJetPhiPhiMoment", &tJetPhiPhiMoment);
   //  original->SetBranchAddress("tJetPt", &tJetPt);
   //  original->SetBranchAddress("tLeadTrackPt", &tLeadTrackPt);
   //  original->SetBranchAddress("tLowestMll", &tLowestMll);
   //  original->SetBranchAddress("tMass", &tMass);
   //  original->SetBranchAddress("tMass_TauEnDown", &tMass_TauEnDown);
   //  original->SetBranchAddress("tMass_TauEnUp", &tMass_TauEnUp);
   //  original->SetBranchAddress("tMatchesDoubleTau32Filter", &tMatchesDoubleTau32Filter);
   //  original->SetBranchAddress("tMatchesDoubleTau32Path", &tMatchesDoubleTau32Path);
   //  original->SetBranchAddress("tMatchesDoubleTau35Filter", &tMatchesDoubleTau35Filter);
   //  original->SetBranchAddress("tMatchesDoubleTau35Path", &tMatchesDoubleTau35Path);
   //  original->SetBranchAddress("tMatchesDoubleTau40Filter", &tMatchesDoubleTau40Filter);
   //  original->SetBranchAddress("tMatchesDoubleTau40Path", &tMatchesDoubleTau40Path);
   //  original->SetBranchAddress("tMatchesDoubleTauCmbIso35RegFilter", &tMatchesDoubleTauCmbIso35RegFilter);
   //  original->SetBranchAddress("tMatchesDoubleTauCmbIso35RegPath", &tMatchesDoubleTauCmbIso35RegPath);
   //  original->SetBranchAddress("tMatchesDoubleTauCmbIso40Filter", &tMatchesDoubleTauCmbIso40Filter);
   //  original->SetBranchAddress("tMatchesDoubleTauCmbIso40Path", &tMatchesDoubleTauCmbIso40Path);
   //  original->SetBranchAddress("tMatchesDoubleTauCmbIso40RegFilter", &tMatchesDoubleTauCmbIso40RegFilter);
   //  original->SetBranchAddress("tMatchesDoubleTauCmbIso40RegPath", &tMatchesDoubleTauCmbIso40RegPath);
   //  original->SetBranchAddress("tMatchesEle24Tau20Filter", &tMatchesEle24Tau20Filter);
   //  original->SetBranchAddress("tMatchesEle24Tau20L1Path", &tMatchesEle24Tau20L1Path);
   //  original->SetBranchAddress("tMatchesEle24Tau20Path", &tMatchesEle24Tau20Path);
   //  original->SetBranchAddress("tMatchesEle24Tau20sL1Filter", &tMatchesEle24Tau20sL1Filter);
   //  original->SetBranchAddress("tMatchesEle24Tau30Filter", &tMatchesEle24Tau30Filter);
   //  original->SetBranchAddress("tMatchesEle24Tau30Path", &tMatchesEle24Tau30Path);
   //  original->SetBranchAddress("tMatchesMu19Tau20Filter", &tMatchesMu19Tau20Filter);
   //  original->SetBranchAddress("tMatchesMu19Tau20Path", &tMatchesMu19Tau20Path);
   //  original->SetBranchAddress("tMatchesMu19Tau20sL1Filter", &tMatchesMu19Tau20sL1Filter);
   //  original->SetBranchAddress("tMatchesMu19Tau20sL1Path", &tMatchesMu19Tau20sL1Path);
   //  original->SetBranchAddress("tMatchesMu21Tau20sL1Filter", &tMatchesMu21Tau20sL1Filter);
   //  original->SetBranchAddress("tMatchesMu21Tau20sL1Path", &tMatchesMu21Tau20sL1Path);
   //  original->SetBranchAddress("tMtToPfMet_ElectronEnDown", &tMtToPfMet_ElectronEnDown);
   //  original->SetBranchAddress("tMtToPfMet_ElectronEnUp", &tMtToPfMet_ElectronEnUp);
   //  original->SetBranchAddress("tMtToPfMet_JetEnDown", &tMtToPfMet_JetEnDown);
   //  original->SetBranchAddress("tMtToPfMet_JetEnUp", &tMtToPfMet_JetEnUp);
   //  original->SetBranchAddress("tMtToPfMet_JetResDown", &tMtToPfMet_JetResDown);
   //  original->SetBranchAddress("tMtToPfMet_JetResUp", &tMtToPfMet_JetResUp);
   //  original->SetBranchAddress("tMtToPfMet_MuonEnDown", &tMtToPfMet_MuonEnDown);
   //  original->SetBranchAddress("tMtToPfMet_MuonEnUp", &tMtToPfMet_MuonEnUp);
   //  original->SetBranchAddress("tMtToPfMet_PhotonEnDown", &tMtToPfMet_PhotonEnDown);
   //  original->SetBranchAddress("tMtToPfMet_PhotonEnUp", &tMtToPfMet_PhotonEnUp);
   //  original->SetBranchAddress("tMtToPfMet_Raw", &tMtToPfMet_Raw);
   //  original->SetBranchAddress("tMtToPfMet_TauEnDown", &tMtToPfMet_TauEnDown);
   //  original->SetBranchAddress("tMtToPfMet_TauEnUp", &tMtToPfMet_TauEnUp);
   //  original->SetBranchAddress("tMtToPfMet_UnclusteredEnDown", &tMtToPfMet_UnclusteredEnDown);
   //  original->SetBranchAddress("tMtToPfMet_UnclusteredEnUp", &tMtToPfMet_UnclusteredEnUp);
   //  original->SetBranchAddress("tMuOverlap", &tMuOverlap);
   //  original->SetBranchAddress("tMuonIdIsoStdVtxOverlap", &tMuonIdIsoStdVtxOverlap);
   //  original->SetBranchAddress("tMuonIdIsoVtxOverlap", &tMuonIdIsoVtxOverlap);
   //  original->SetBranchAddress("tMuonIdVtxOverlap", &tMuonIdVtxOverlap);
   //  original->SetBranchAddress("tNChrgHadrIsolationCands", &tNChrgHadrIsolationCands);
   //  original->SetBranchAddress("tNChrgHadrSignalCands", &tNChrgHadrSignalCands);
   //  original->SetBranchAddress("tNGammaSignalCands", &tNGammaSignalCands);
   //  original->SetBranchAddress("tNNeutralHadrSignalCands", &tNNeutralHadrSignalCands);
   //  original->SetBranchAddress("tNSignalCands", &tNSignalCands);
   //  original->SetBranchAddress("tNearestZMass", &tNearestZMass);
   //  original->SetBranchAddress("tNeutralIsoPtSumWeight", &tNeutralIsoPtSumWeight);
   //  original->SetBranchAddress("tNeutralIsoPtSumWeightdR03", &tNeutralIsoPtSumWeightdR03);
   //  original->SetBranchAddress("tNeutralIsoPtSumdR03", &tNeutralIsoPtSumdR03);
   //  original->SetBranchAddress("tPhi", &tPhi);
   //  original->SetBranchAddress("tPhi_TauEnDown", &tPhi_TauEnDown);
   //  original->SetBranchAddress("tPhi_TauEnUp", &tPhi_TauEnUp);
   //  original->SetBranchAddress("tPhotonPtSumOutsideSignalCone", &tPhotonPtSumOutsideSignalCone);
   //  original->SetBranchAddress("tPhotonPtSumOutsideSignalConedR03", &tPhotonPtSumOutsideSignalConedR03);
   //  original->SetBranchAddress("tPt", &tPt);
   //  original->SetBranchAddress("tPt_TauEnDown", &tPt_TauEnDown);
   //  original->SetBranchAddress("tPt_TauEnUp", &tPt_TauEnUp);
   //  original->SetBranchAddress("tRank", &tRank);
   //  original->SetBranchAddress("tRerunMVArun2v1DBoldDMwLTLoose", &tRerunMVArun2v1DBoldDMwLTLoose);
   //  original->SetBranchAddress("tRerunMVArun2v1DBoldDMwLTMedium", &tRerunMVArun2v1DBoldDMwLTMedium);
   //  original->SetBranchAddress("tRerunMVArun2v1DBoldDMwLTTight", &tRerunMVArun2v1DBoldDMwLTTight);
   //  original->SetBranchAddress("tRerunMVArun2v1DBoldDMwLTVLoose", &tRerunMVArun2v1DBoldDMwLTVLoose);
   //  original->SetBranchAddress("tRerunMVArun2v1DBoldDMwLTVTight", &tRerunMVArun2v1DBoldDMwLTVTight);
   //  original->SetBranchAddress("tRerunMVArun2v1DBoldDMwLTVVTight", &tRerunMVArun2v1DBoldDMwLTVVTight);
   //  original->SetBranchAddress("tRerunMVArun2v1DBoldDMwLTraw", &tRerunMVArun2v1DBoldDMwLTraw);
   //  original->SetBranchAddress("tVZ", &tVZ);
   //  original->SetBranchAddress("tZTTGenDR", &tZTTGenDR);
   //  original->SetBranchAddress("tZTTGenEta", &tZTTGenEta);
   //  original->SetBranchAddress("tZTTGenPhi", &tZTTGenPhi);
   //  original->SetBranchAddress("tZTTGenPt", &tZTTGenPt);
   //  original->SetBranchAddress("t_e_collinearmass", &t_e_collinearmass);
   //  original->SetBranchAddress("t_e_collinearmass_JetEnDown", &t_e_collinearmass_JetEnDown);
   //  original->SetBranchAddress("t_e_collinearmass_JetEnUp", &t_e_collinearmass_JetEnUp);
   //  original->SetBranchAddress("t_e_collinearmass_UnclusteredEnDown", &t_e_collinearmass_UnclusteredEnDown);
   //  original->SetBranchAddress("t_e_collinearmass_UnclusteredEnUp", &t_e_collinearmass_UnclusteredEnUp);
   //  original->SetBranchAddress("tauVetoPt20TightMVALTVtx", &tauVetoPt20TightMVALTVtx);
   //  original->SetBranchAddress("tripleEGroup", &tripleEGroup);
   //  original->SetBranchAddress("tripleEPass", &tripleEPass);
   //  original->SetBranchAddress("tripleEPrescale", &tripleEPrescale);
   //  original->SetBranchAddress("tripleMuGroup", &tripleMuGroup);
   //  original->SetBranchAddress("tripleMuPass", &tripleMuPass);
   //  original->SetBranchAddress("tripleMuPrescale", &tripleMuPrescale);
   //
   //  original->SetBranchAddress("vbfDijetrap", &vbfDijetrap);
   //  original->SetBranchAddress("vbfDijetrap_JetEnDown", &vbfDijetrap_JetEnDown);
   //  original->SetBranchAddress("vbfDijetrap_JetEnUp", &vbfDijetrap_JetEnUp);
   //
   //  original->SetBranchAddress("vbfDphihj", &vbfDphihj);
   //  original->SetBranchAddress("vbfDphihj_JetEnDown", &vbfDphihj_JetEnDown);
   //  original->SetBranchAddress("vbfDphihj_JetEnUp", &vbfDphihj_JetEnUp);
   //  original->SetBranchAddress("vbfDphihjnomet", &vbfDphihjnomet);
   //  original->SetBranchAddress("vbfDphihjnomet_JetEnDown", &vbfDphihjnomet_JetEnDown);
   //  original->SetBranchAddress("vbfDphihjnomet_JetEnUp", &vbfDphihjnomet_JetEnUp);
   //  original->SetBranchAddress("vbfHrap", &vbfHrap);
   //  original->SetBranchAddress("vbfHrap_JetEnDown", &vbfHrap_JetEnDown);
   //  original->SetBranchAddress("vbfHrap_JetEnUp", &vbfHrap_JetEnUp);
   //
   //  original->SetBranchAddress("vbfMVA", &vbfMVA);
   //  original->SetBranchAddress("vbfMVA_JetEnDown", &vbfMVA_JetEnDown);
   //  original->SetBranchAddress("vbfMVA_JetEnUp", &vbfMVA_JetEnUp);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteFlavMapDown", &vbfMass_JetAbsoluteFlavMapDown);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteFlavMapUp", &vbfMass_JetAbsoluteFlavMapUp);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteMPFBiasDown", &vbfMass_JetAbsoluteMPFBiasDown);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteMPFBiasUp", &vbfMass_JetAbsoluteMPFBiasUp);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteScaleDown", &vbfMass_JetAbsoluteScaleDown);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteScaleUp", &vbfMass_JetAbsoluteScaleUp);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteStatDown", &vbfMass_JetAbsoluteStatDown);
   //  original->SetBranchAddress("vbfMass_JetAbsoluteStatUp", &vbfMass_JetAbsoluteStatUp);
   //  original->SetBranchAddress("vbfMass_JetClosureDown", &vbfMass_JetClosureDown);
   //  original->SetBranchAddress("vbfMass_JetClosureUp", &vbfMass_JetClosureUp);
   //  original->SetBranchAddress("vbfMass_JetFlavorQCDDown", &vbfMass_JetFlavorQCDDown);
   //  original->SetBranchAddress("vbfMass_JetFlavorQCDUp", &vbfMass_JetFlavorQCDUp);
   //  original->SetBranchAddress("vbfMass_JetFragmentationDown", &vbfMass_JetFragmentationDown);
   //  original->SetBranchAddress("vbfMass_JetFragmentationUp", &vbfMass_JetFragmentationUp);
   //  original->SetBranchAddress("vbfMass_JetPileUpDataMCDown", &vbfMass_JetPileUpDataMCDown);
   //  original->SetBranchAddress("vbfMass_JetPileUpDataMCUp", &vbfMass_JetPileUpDataMCUp);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtBBDown", &vbfMass_JetPileUpPtBBDown);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtBBUp", &vbfMass_JetPileUpPtBBUp);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtEC1Down", &vbfMass_JetPileUpPtEC1Down);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtEC1Up", &vbfMass_JetPileUpPtEC1Up);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtEC2Down", &vbfMass_JetPileUpPtEC2Down);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtEC2Up", &vbfMass_JetPileUpPtEC2Up);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtHFDown", &vbfMass_JetPileUpPtHFDown);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtHFUp", &vbfMass_JetPileUpPtHFUp);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtRefDown", &vbfMass_JetPileUpPtRefDown);
   //  original->SetBranchAddress("vbfMass_JetPileUpPtRefUp", &vbfMass_JetPileUpPtRefUp);
   //  original->SetBranchAddress("vbfMass_JetRelativeBalDown", &vbfMass_JetRelativeBalDown);
   //  original->SetBranchAddress("vbfMass_JetRelativeBalUp", &vbfMass_JetRelativeBalUp);
   //  original->SetBranchAddress("vbfMass_JetRelativeFSRDown", &vbfMass_JetRelativeFSRDown);
   //  original->SetBranchAddress("vbfMass_JetRelativeFSRUp", &vbfMass_JetRelativeFSRUp);
   //  original->SetBranchAddress("vbfMass_JetRelativeJEREC1Down", &vbfMass_JetRelativeJEREC1Down);
   //  original->SetBranchAddress("vbfMass_JetRelativeJEREC1Up", &vbfMass_JetRelativeJEREC1Up);
   //  original->SetBranchAddress("vbfMass_JetRelativeJEREC2Down", &vbfMass_JetRelativeJEREC2Down);
   //  original->SetBranchAddress("vbfMass_JetRelativeJEREC2Up", &vbfMass_JetRelativeJEREC2Up);
   //  original->SetBranchAddress("vbfMass_JetRelativeJERHFDown", &vbfMass_JetRelativeJERHFDown);
   //  original->SetBranchAddress("vbfMass_JetRelativeJERHFUp", &vbfMass_JetRelativeJERHFUp);
   //  original->SetBranchAddress("vbfMass_JetRelativePtBBDown", &vbfMass_JetRelativePtBBDown);
   //  original->SetBranchAddress("vbfMass_JetRelativePtBBUp", &vbfMass_JetRelativePtBBUp);
   //  original->SetBranchAddress("vbfMass_JetRelativePtEC1Down", &vbfMass_JetRelativePtEC1Down);
   //  original->SetBranchAddress("vbfMass_JetRelativePtEC1Up", &vbfMass_JetRelativePtEC1Up);
   //  original->SetBranchAddress("vbfMass_JetRelativePtEC2Down", &vbfMass_JetRelativePtEC2Down);
   //  original->SetBranchAddress("vbfMass_JetRelativePtEC2Up", &vbfMass_JetRelativePtEC2Up);
   //  original->SetBranchAddress("vbfMass_JetRelativePtHFDown", &vbfMass_JetRelativePtHFDown);
   //  original->SetBranchAddress("vbfMass_JetRelativePtHFUp", &vbfMass_JetRelativePtHFUp);
   //  original->SetBranchAddress("vbfMass_JetRelativeStatECDown", &vbfMass_JetRelativeStatECDown);
   //  original->SetBranchAddress("vbfMass_JetRelativeStatECUp", &vbfMass_JetRelativeStatECUp);
   //  original->SetBranchAddress("vbfMass_JetRelativeStatFSRDown", &vbfMass_JetRelativeStatFSRDown);
   //  original->SetBranchAddress("vbfMass_JetRelativeStatFSRUp", &vbfMass_JetRelativeStatFSRUp);
   //  original->SetBranchAddress("vbfMass_JetRelativeStatHFDown", &vbfMass_JetRelativeStatHFDown);
   //  original->SetBranchAddress("vbfMass_JetRelativeStatHFUp", &vbfMass_JetRelativeStatHFUp);
   //  original->SetBranchAddress("vbfMass_JetSinglePionECALDown", &vbfMass_JetSinglePionECALDown);
   //  original->SetBranchAddress("vbfMass_JetSinglePionECALUp", &vbfMass_JetSinglePionECALUp);
   //  original->SetBranchAddress("vbfMass_JetSinglePionHCALDown", &vbfMass_JetSinglePionHCALDown);
   //  original->SetBranchAddress("vbfMass_JetSinglePionHCALUp", &vbfMass_JetSinglePionHCALUp);
   //  original->SetBranchAddress("vbfMass_JetSubTotalAbsoluteDown", &vbfMass_JetSubTotalAbsoluteDown);
   //  original->SetBranchAddress("vbfMass_JetSubTotalAbsoluteUp", &vbfMass_JetSubTotalAbsoluteUp);
   //  original->SetBranchAddress("vbfMass_JetSubTotalMCDown", &vbfMass_JetSubTotalMCDown);
   //  original->SetBranchAddress("vbfMass_JetSubTotalMCUp", &vbfMass_JetSubTotalMCUp);
   //  original->SetBranchAddress("vbfMass_JetSubTotalPileUpDown", &vbfMass_JetSubTotalPileUpDown);
   //  original->SetBranchAddress("vbfMass_JetSubTotalPileUpUp", &vbfMass_JetSubTotalPileUpUp);
   //  original->SetBranchAddress("vbfMass_JetSubTotalPtDown", &vbfMass_JetSubTotalPtDown);
   //  original->SetBranchAddress("vbfMass_JetSubTotalPtUp", &vbfMass_JetSubTotalPtUp);
   //  original->SetBranchAddress("vbfMass_JetSubTotalRelativeDown", &vbfMass_JetSubTotalRelativeDown);
   //  original->SetBranchAddress("vbfMass_JetSubTotalRelativeUp", &vbfMass_JetSubTotalRelativeUp);
   //  original->SetBranchAddress("vbfMass_JetSubTotalScaleDown", &vbfMass_JetSubTotalScaleDown);
   //  original->SetBranchAddress("vbfMass_JetSubTotalScaleUp", &vbfMass_JetSubTotalScaleUp);
   //  original->SetBranchAddress("vbfMass_JetTimePtEtaDown", &vbfMass_JetTimePtEtaDown);
   //  original->SetBranchAddress("vbfMass_JetTimePtEtaUp", &vbfMass_JetTimePtEtaUp);
   //  original->SetBranchAddress("vbfMass_JetTotalDown", &vbfMass_JetTotalDown);
   //  original->SetBranchAddress("vbfMass_JetTotalUp", &vbfMass_JetTotalUp);
   //  original->SetBranchAddress("vbfNJets20", &vbfNJets20);
   //  original->SetBranchAddress("vbfNJets20_JetEnDown", &vbfNJets20_JetEnDown);
   //  original->SetBranchAddress("vbfNJets20_JetEnUp", &vbfNJets20_JetEnUp);
   //  original->SetBranchAddress("vbfNJets30", &vbfNJets30);
   //  original->SetBranchAddress("vbfNJets30_JetEnDown", &vbfNJets30_JetEnDown);
   //  original->SetBranchAddress("vbfNJets30_JetEnUp", &vbfNJets30_JetEnUp);
   //  original->SetBranchAddress("vbfVispt", &vbfVispt);
   //  original->SetBranchAddress("vbfVispt_JetEnDown", &vbfVispt_JetEnDown);
   //  original->SetBranchAddress("vbfVispt_JetEnUp", &vbfVispt_JetEnUp);
   //  original->SetBranchAddress("vbfdijetpt", &vbfdijetpt);
   //  original->SetBranchAddress("vbfdijetpt_JetEnDown", &vbfdijetpt_JetEnDown);
   //  original->SetBranchAddress("vbfdijetpt_JetEnUp", &vbfdijetpt_JetEnUp);
   //  original->SetBranchAddress("vbfj1eta", &vbfj1eta);
   //  original->SetBranchAddress("vbfj1eta_JetEnDown", &vbfj1eta_JetEnDown);
   //  original->SetBranchAddress("vbfj1eta_JetEnUp", &vbfj1eta_JetEnUp);
   //  original->SetBranchAddress("vbfj1pt", &vbfj1pt);
   //  original->SetBranchAddress("vbfj1pt_JetEnDown", &vbfj1pt_JetEnDown);
   //  original->SetBranchAddress("vbfj1pt_JetEnUp", &vbfj1pt_JetEnUp);
   //  original->SetBranchAddress("vbfj2eta", &vbfj2eta);
   //  original->SetBranchAddress("vbfj2eta_JetEnDown", &vbfj2eta_JetEnDown);
   //  original->SetBranchAddress("vbfj2eta_JetEnUp", &vbfj2eta_JetEnUp);
   //  original->SetBranchAddress("vbfj2pt", &vbfj2pt);
   //  original->SetBranchAddress("vbfj2pt_JetEnDown", &vbfj2pt_JetEnDown);
   //  original->SetBranchAddress("vbfj2pt_JetEnUp", &vbfj2pt_JetEnUp);
   //  original->SetBranchAddress("idx", &idx);
}

TTree* etau_tree::do_skimming() {
  Int_t nevt = (Int_t)original->GetEntries();
  for (auto i = 0; i < nevt; i++) {
    original->GetEntry(i);

    if (d0_1 > 0.045 || dZ_1 < 0.2 || !eMVANonTrigWP80 || !ePassesConversionVeto || eMissingHits > 1 || eVetoZTTp001dxyzR0 > 1 || ePt < 25 || abs(eEta) > 2.5)
      continue;
    if (dZ_2 > 0.2 || !byMediumIsolationMVArun2v1DBoldDMwLT_2 || !decayModeFinding_2 || abs(q_2) > 1 || tPt < 19 || abs(tEta) > 2.3)
      continue;
    if (muVetoZTTp001dxyzR0 > 0)
      continue;
    if (e_t_DR < 0.5 || dielectronVeto > 0)
      continue;

    met_px = met*cos(metphi);
    met_py = met*sin(metphi);

    extraelec_veto = eVetoZTTp001dxyzR0 > 1;
    extramuon_veto = muVetoZTTp001dxyzR0 > 0;
    dilepton_veto = dielectronVeto > 0;

    TLorentzVector ele;
    TLorentzVector tau;
    ele.SetPtEtaPhiM(ePt, eEta, ePhi, eMass);
    tau.SetPtEtaPhiM(tPt, tEta, tPhi, tMass);

    m_1 = ele.M();
    px_1 = ele.Px();
    py_1 = ele.Py();
    pz_1 = ele.Pz();
    e_1 = ele.E();
    pt_1 = ele.Pt();
    phi_1 = ele.Phi();
    eta_1 = ele.Eta();
    m_2 = tau.M();
    px_2 = tau.Px();
    py_2 = tau.Py();
    pz_2 = tau.Pz();
    e_2 = tau.E();
    pt_2 = tau.Pt();
    phi_2 = tau.Phi();
    eta_2 = tau.Eta();

    TLorentzVector h = ele + tau;
    TLorentzVector jet1;
    if (njetspt20 > 0 && jpt_1>0)
       jet1.SetPtEtaPhiM(jpt_1,jeta_1,jphi_1,0);
    TLorentzVector jet2;
    if (njetspt20 > 1 && jpt_2>0)
       jet2.SetPtEtaPhiM(jpt_2,jeta_2,jphi_2,0);
    TLorentzVector dijet=jet1+jet2;

    if (njetspt20 > 1){
       jdeta = vbfDeta;
       jdphi = vbfDphi;
       dijetphi = dijet.Phi();
       hdijetphi = h.DeltaPhi(dijet);
       visjeteta = h.Eta()-dijet.Eta();
       mjj = vbfMass;
       njetingap20 = vbfJetVeto20;
       njetingap = vbfJetVeto30;
    }
    else{
       jdphi = -10000;
       jdeta = -10000;
       dijetpt = -10000;
       dijetphi = -10000;
       hdijetphi = -10000;
       visjeteta = -10000;
       mjj = -10000;
       njetingap20 = -10000;
       njetingap = -100000;
    }
    if (njetspt20_JESUp > 1){
       njetingap20_JESUp = vbfJetVeto20_JetEnUp;
       njetingap_JESUp = vbfJetVeto30_JetEnUp;
       mjj_JESUp = vbfMass_JetEnUp;
       jdeta_JESUp = vbfDeta_JetEnUp;
    }
    else{
       jdeta_JESUp = -10000;
       mjj_JESUp = -10000;
       njetingap20_JESUp = -10000;
       njetingap_JESUp = -100000;
    }
    if (njetspt20_JESDown > 1){
       njetingap20_JESDown = vbfJetVeto20_JetEnDown;
       njetingap_JESDown = vbfJetVeto30_JetEnDown;
       mjj_JESDown = vbfMass_JetEnDown;
       jdeta_JESDown = vbfDeta_JetEnDown;
    }
    else{
       jdeta_JESDown  = -10000;
       mjj_JESDown  = -10000;
       njetingap20_JESDown  = -10000;
       njetingap_JESDown  = -100000;
    }

  isZet = isZtt && fabs(eGenPdgId) == 11;

    tree->Fill();
  }
  return tree;
}
