#include <map>

static std::map<std::string, std::string> samples = {
  {"test", "root_files"},



  // {"dy_v1", "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY1JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  // {"dy_v2", "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY2JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  // {"dy_v3", "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY3JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  // {"dy_v4", "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY4JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},

  {"dy1_M-10to50"             , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY1JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"dy1_M-50"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"dy2_M-10to50"             , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY2JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"dy2_M-50"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"dy3_M-10to50"             , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"dy3_M-50"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"dy4_M-10to50"             , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"dy4_M-50"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6_ext1-v2"},
  {"DY_M-50"                  , "/hdfs/store/user/caillol/SMHTT_mc_feb13/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6_ext2-v1"},
  {"EWKMinus"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKWMinus2Jets_WToLNu_M-50_13TeV-madgraph-pythia8_v6-v1"},
  {"EWKMinus_ext1"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKWMinus2Jets_WToLNu_M-50_13TeV-madgraph-pythia8_v6_ext1-v1"},
  {"EWKMinus_ext2"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKWMinus2Jets_WToLNu_M-50_13TeV-madgraph-pythia8_v6_ext2-v1"},
  {"EWKPlus"                  , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKWPlus2Jets_WToLNu_M-50_13TeV-madgraph-pythia8_v6-v1"},
  {"EWKPlus_ext1"             , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKWPlus2Jets_WToLNu_M-50_13TeV-madgraph-pythia8_v6_ext1-v1"},
  {"EWKPlus_ext2"             , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKWPlus2Jets_WToLNu_M-50_13TeV-madgraph-pythia8_v6_ext2-v1"},
  {"EWKZLL"                   , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKZ2Jets_ZToLL_M-50_13TeV-madgraph-pythia8_v6-v1"},
  {"EWKZLL_ext1"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKZ2Jets_ZToLL_M-50_13TeV-madgraph-pythia8_v6_ext1-v1"},
  {"EWKZLL_ext2"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKZ2Jets_ZToLL_M-50_13TeV-madgraph-pythia8_v6_ext2-v1"},
  {"EWKZNuNu"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKZ2Jets_ZToNuNu_13TeV-madgraph-pythia8_v6-v1"},
  {"EWKZNuNu_ext1"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKZ2Jets_ZToNuNu_13TeV-madgraph-pythia8_v6_ext1-v1"},
  {"EWKZNuNu_ext2"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/EWKZ2Jets_ZToNuNu_13TeV-madgraph-pythia8_v6_ext2-v1"},
  {"GluGluToTauTau_M110"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGluHToTauTau_M110_13TeV_powheg_pythia8_v6-v1"},
  {"GluGluToTauTau_M125"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGluHToTauTau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"GluGluToTauTau_M130"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGluHToTauTau_M130_13TeV_powheg_pythia8_v6_ext1-v1"},
  {"GluGluToTauTau_M140"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGluHToTauTau_M140_13TeV_powheg_pythia8_v6-v1"},
  {"GluGluToWW_M125"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGluHToWWTo2L2Nu_M125_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToETau_M120"  , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToETau_M120_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToETau_M125"  , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToETau_M130"  , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToETau_M130_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToETau_M150"  , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToETau_M150_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToMuTau_M120" , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToMuTau_M120_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToMuTau_M125" , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToMuTau_M130" , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToMuTau_M130_13TeV_powheg_pythia8_v6-v1"},
  {"GluGlu_LFV_HToMuTau_M150" , "/hdfs/store/user/caillol/SMHTT_mc_feb13/GluGlu_LFV_HToMuTau_M150_13TeV_powheg_pythia8_v6-v1"},
  {"ST_t-channel_antitop"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1_v6-v1"},
  {"ST_t-channel_top"         , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1_v6-v1"},
  {"ST_tW_antitop"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_v6_ext1-v1"},
  {"ST_tW_top"                , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_v6_ext1-v1"},
  {"TT_evtgen"                , "/hdfs/store/user/caillol/SMHTT_mc_feb13/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8-evtgen_v6-v1"},
  {"TT"                       , "/hdfs/store/user/caillol/SMHTT_mc_feb13/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_v6-v1"},
  {"VBFHToTauTau_M110"        , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBFHToTauTau_M110_13TeV_powheg_pythia8_v6-v1"},
  {"VBFHToTauTau_M120"        , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBFHToTauTau_M120_13TeV_powheg_pythia8_v6_ext1-v1"},
  {"VBFHToTauTau_M125"        , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBFHToTauTau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"VBFHToTauTau_M130"        , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBFHToTauTau_M130_13TeV_powheg_pythia8_v6_ext1-v1"},
  {"VBFHToTauTau_M140"        , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBFHToTauTau_M140_13TeV_powheg_pythia8_v6-v1"},
  {"VBFHToWWTo2L2Nu_M125"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBFHToWWTo2L2Nu_M125_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToETau_M120"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToETau_M120_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToETau_M125"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToETau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToETau_M130"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToETau_M130_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToETau_M150"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToETau_M150_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToMuTau_M120"    , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToMuTau_M120_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToMuTau_M125"    , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToMuTau_M130"    , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToMuTau_M130_13TeV_powheg_pythia8_v6-v1"},
  {"VBF_LFV_HToMuTau_M150"    , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VBF_LFV_HToMuTau_M150_13TeV_powheg_pythia8_v6-v1"},
  {"VVTo2L2Nu"                , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8_v6-v1"},
  {"VVTo2L2Nu_ext1"           , "/hdfs/store/user/caillol/SMHTT_mc_feb13/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8_v6_ext1-v1"},
  {"W1JetsToLNu"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"W2JetsToLNu"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"W2JetsToLNu_ext1"         , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6_ext1-v1"},
  {"W3JetsToLNu"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"W3JetsToLNu_ext1"         , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6_ext1-v1"},
  {"W4JetsToLNu"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"W4JetsToLNu_ext1"         , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6_ext1-v1"},
  {"W4JetsToLNu_ext2"         , "/hdfs/store/user/caillol/SMHTT_mc_feb13/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6_ext2-v1"},
  {"WGToLNuG_ext1"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_v6_ext1-v1"},
  {"WGToLNuG_ext2"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_v6_ext2-v1"},
  {"WGstarToLNuEE"            , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WGstarToLNuEE_012Jets_13TeV-madgraph_v6-v1"},
  {"WGstarToLNuMuMu"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WGstarToLNuMuMu_012Jets_13TeV-madgraph_v6-v1"},
  {"WJetsToLNu"               , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6-v1"},
  {"WJetsToLNu_ext2"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v6_ext2-v1"},
  {"WWTo1L1Nu2Q"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8_v6-v1"},
  {"WWW_4F"                   , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WWW_4F_TuneCUETP8M1_13TeV-amcatnlo-pythia8_v6-v1"},
  {"WZJToLLLNu"               , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8_v6-v1"},
  {"WZTo1L1Nu2Q"              , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8_v6-v3"},
  {"WZTo1L3Nu"                , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8_v6-v1"},
  {"WZTo2L2Q"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8_v6-v1"},
  {"WminusHToTauTau_M110"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WminusHToTauTau_M110_13TeV_powheg_pythia8_v6-v1"},
  {"WminusHToTauTau_M120"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WminusHToTauTau_M120_13TeV_powheg_pythia8_v6-v1"},
  {"WminusHToTauTau_M125"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WminusHToTauTau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"WminusHToTauTau_M130"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WminusHToTauTau_M130_13TeV_powheg_pythia8_v6-v1"},
  {"WminusHToTauTau_M140"     , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WminusHToTauTau_M140_13TeV_powheg_pythia8_v6-v1"},
  {"WplusHToTauTau_M110"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WplusHToTauTau_M110_13TeV_powheg_pythia8_v6-v1"},
  {"WplusHToTauTau_M120"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WplusHToTauTau_M120_13TeV_powheg_pythia8_v6-v1"},
  {"WplusHToTauTau_M125"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WplusHToTauTau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"WplusHToTauTau_M130"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WplusHToTauTau_M130_13TeV_powheg_pythia8_v6-v1"},
  {"WplusHToTauTau_M140"      , "/hdfs/store/user/caillol/SMHTT_mc_feb13/WplusHToTauTau_M140_13TeV_powheg_pythia8_v6-v1"},
  {"ZHToTauTau_M120"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ZHToTauTau_M120_13TeV_powheg_pythia8_v6-v1"},
  {"ZHToTauTau_M125"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ZHToTauTau_M125_13TeV_powheg_pythia8_v6-v1"},
  {"ZHToTauTau_M130"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ZHToTauTau_M130_13TeV_powheg_pythia8_v6-v1"},
  {"ZHToTauTau_M140"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ZHToTauTau_M140_13TeV_powheg_pythia8_v6-v1"},
  {"ZZTo2L2Q"                 , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8_v6-v1"},
  {"ZZTo4L"                   , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ZZTo4L_13TeV-amcatnloFXFX-pythia8_v6_ext1-v1"},
  {"ttHJetToTT_M125"          , "/hdfs/store/user/caillol/SMHTT_mc_feb13/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8_v6_ext4-v1"},
  {"ZZ"                       , "/hdfs/store/user/tmitchel/mc2017_ntuples_Jun18/ZZ_TuneCP5_13TeV-pythia8_v14-v1"},
  {"sync"                     , "/hdfs/store/user/tmitchel"},


};
